### ISSUE TITLE
Make fbjs a dev dependency

### ISSUE THREAD

**Issue by philipp-spiess** [facebook/draft-js#1002]
This is a proposal to make `fbjs` a `devDependency` and not a `dependency`.

When I grep for `fbjs` in the current master, I find a couple of hits but only one requires the actual `fbjs` module: https://github.com/facebook/draft-js/blob/master/scripts/module-map.js#L20

Since this file is apparently a script that is needed for running tests, I think we should declare `fbjs` a devDependency (the same way [react does](https://github.com/facebook/react/blob/master/package.json#L50)).

**Comment by colinjeanne** [comment]
`fbjs` is not a dev dependency. The file you listed maps the `fbjs` modules so that they can be used throughout Draft without needing to specify a relative path. Various parts of `fbjs` are used throughout the codebase, such as [UserAgent](https://github.com/facebook/fbjs/tree/master/packages/fbjs/src/useragent) in [these locations](https://github.com/facebook/draft-js/search?utf8=✓&q=UserAgent).

**Comment by philipp-spiess** [comment]
@colinjeanne Thank you for clarifying. Since `scripts` also contains a folder `jest` I thought that those were only meant to be exposed in tests. I'll close this now 👍
