### ISSUE TITLE
[RFC] ContentState.getSelectionAfter is different than EditorState.getSelection when moving the cursor

### ISSUE THREAD

**Issue by cgestes** [facebook/draft-js#103]
I understand that moving the cursor does not generate a rerender of ContentState, explaining why it is not updated.

I was expecting to be able to use ContentState.getSelectionAfter to chain operations on the content like this:

contentState = myChange1(contentState, optionalSelection);
contentState = myChange2(contentState, optionalSelection);
contentState = myChange3(contentState, optionalSelection);
editorState.push(editorState, contentState, 'atomic-changes');

Does my pattern make sense?

I'am forced to pass the selection as a parameter and to get it back instead of using the one in contentState.getSelectionStateAfter for now.

I understand selectionBefore should not change to support undo properly. (to put the cursor back to the last non cursor edition).

Would it make sense to update selectionAfter for each changes?

**Comment by hellendag** [comment]
> I understand selectionBefore should not change to support undo properly.

The key here is that `selectionAfter` is similarly important for `redo` behavior -- when replaying a `ContentState`, we have to know where to put the cursor immediately afterward. Cursor changes that do not affect the contents therefore cannot always be applied to the current `ContentState`.

For `Modifier` functions, we cannot necessarily know the target selection of the operation. It may sometimes make sense to allow it to be optional, but I prefer being explicit about the target rather than relying on the `selectionAfter` -- that value may have no relationship to the current cursor position.

**Comment by cgestes** [comment]
Ok, so I need to return a selection in modifiers functions.

If the modifier actually do not change the selection ContentState.selectionAfter will not be correct.

I will also run into troubles with Draft modifiers functions that only return a ContentState but do not actually change the state. `removeRangeFromContentState` is an example.

**Comment by hellendag** [comment]
I may not fully understand your use case here.

The `ContentState` object returned by a modifier should include `selectionBefore`/`selectionAfter` values that are relevant to that `ContentState`'s undo/redo behavior. In your case, it sounds like you are making a change that should put the cursor somewhere different, after the content change has been performed. Do I have that correct?

If so, what you could do is:

1. Create a `ContentState` that sets the appropriate `selectionBefore`/`selectionAfter`, and use `EditorState.push` with that.
2. Then, move the cursor to your required location by using `EditorState.forceSelection`.

Since the current cursor belongs to the `EditorState`, not the `ContentState`, that is where it would belong.

> I will also run into troubles with Draft modifiers functions that only return a ContentState but do not actually change the state. removeRangeFromContentState is an example.

Do you have details on where this is causing problems for your use case?

**Comment by cgestes** [comment]
I want to be able to call easily multiples modifiers in a single transaction.

So to perform the second action I need to know the resulting selection from the previous one, which can be:
- the returned contentState.selectionAfter (if the modifier did something)
- the selection passed as parameter to the modifier (if the modifier did nothing)

it adds a lot of boilerplate, It would be easier to get that information from contentState.

Maybe the selection itself could be moved to contentState.

(passing editorState is not appropriated as I dont want to push after each calls to a modifier)

**Comment by hellendag** [comment]
> (passing editorState is not appropriated as I dont want to push after each calls to a modifier)

Right. You only want to push something that should be a boundary state. That was my assumption here, because that's the usefulness of `selectionBefore`/`selectionAfter`.

If you don't care about a given `ContentState` serving as a boundary state, and are only using it as an intermediate state for a series of transactions, then you can set its `selectionAfter` to whatever you need, using `myContentState.set` or `myContentState.merge`. If this makes your custom modifier functions easier for you to use, then you should feel free to do this. :) (Based on your description, I assume you are writing custom modifier functions.)

I do not, however, believe that the `selectionBefore` or `selectionAfter` properties should always be used as target selections for modifier functions. That is not their aim.

In any case, if at the end of your modifiers, you wish to set the current `SelectionState` to something other than the `selectionAfter` of your final `ContentState`, then `EditorState.forceSelection` would be the way to do this.

**Comment by cgestes** [comment]
> I do not, however, believe that the selectionBefore or selectionAfter properties should always be used as target selections for modifier functions. That is not their aim.
Sure.

yes I'am writing custom modifiers.

One alternative solution would be to include both contentState and the selection in an immutable Record and use that instead of contentState for the modifier function.

something like:
```javascript

let CurrentContentState = Record({selection, contentState});
function mymodifier(currentContentState) {
  //modify currentContentState
  return currentContentState;
}
```

that would make sense if the selection needs to be updated at the end. (to something different than selectionAfter)

Anyway setting selectionAfter to the current selection when getting contentState sound like a reliable option.

Thank you for your answers.

I guess we can close.

**Comment by hellendag** [comment]
> One alternative solution would be to include both contentState and the selection in an immutable Record and use that instead of contentState for the modifier function.

Yeah, I was thinking about that too. It does seem like it would suit the purpose of having the fallback selection available in the return value. And if that selection is definitely the right target for the next modifier, then it would certainly make sense. (I'm not sure this would always be the case, but perhaps it often would.)

I'm all in favor of converging on the best API for the job, so I'll keep thinking more about it. :) Thanks for your thoughts!
