### ISSUE TITLE
Key of same block changes

### ISSUE THREAD

**Issue by indianscout** [facebook/draft-js#1045]
**Question - possible bug**: Key of same block changes under certain circumstances.

**Problem**: Why does draftjs reuse the key of the deleted _block1_ for _block2_?

**Reproduce with**: 
1. Load https://jsfiddle.net/m6z0xn4r/155/
2. Set focus on editor, state is logged to console and looks like:
![image](https://cloud.githubusercontent.com/assets/7571099/23470819/bb40d428-fea7-11e6-93bd-2b1a5c85ef8d.png)
Important: 
```
key: "4njkf" -> text: "block1"
key:"9576h" -> text: "block2"
```
2. Remove block1 and the editors raw state looks like:
![image](https://cloud.githubusercontent.com/assets/7571099/23471034/4bc1345c-fea8-11e6-965f-e9a1b0772b1e.png)
Important: 
```
key: "4njkf" -> text: "block2"
```

**What is the expected behavior?**: I expect that draftjs keeps the key of block2 (_9576h_). Why gets the key changed? This is a problem in my specific use case because I need the keys to highlight added, deleted and changed blocks. In this case the key of the same and identical content block changes. This makes it difficult to compare content based on the keys.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
This behaviour is not browser specific.

**Comment by colinjeanne** [comment]
This is how removing a range works ([see here](https://github.com/facebook/draft-js/blob/69890ed57b5f4256cc93ae8e9ea178296851a23e/src/model/transaction/removeRangeFromContentState.js#L22)).

You could imagine a solution which removes blocks when they are completely selected but you still will hit edge cases. For example, suppose you selected all but the first character in the first block and only the first character in the second block and pressed backspace. The resulting block's text would be `block2` but it is actually a combination of the text from blocks 1 and 2. Is it not reasonable to keep the first block's ID in this case? Would you want it to keep the ID of block 2 instead because the resulting text is the same?

Comparing content across changes is difficult and how different edge cases are handled depends on the requirements of the diff. That complexity shouldn't be included in the editor.

**Comment by indianscout** [comment]
I see there are other scenarios I did not had in mind.
Thanks for your the feedback.
