### ISSUE TITLE
Why not used ES2005 ?

### ISSUE THREAD

**Issue by Billgo** [facebook/draft-js#107]
Why not used ES2005 ?

**Comment by BerkeleyTrue** [comment]
Do you mean ES2015?

**Comment by Billgo** [comment]
@BerkeleyTrue O Yes , I'm very sorry I was wrong. But I want to ask why not used ES2016 in Project  draft-js  .

**Comment by wolfbeast** [comment]
Because many browsers don't support it fully. it would break web compat in all sorts of colorful ways.

**Comment by spicyj** [comment]
Draft.js does use many ES2015 features, like import/export, arrow functions, and let/const. They are compiled out using Babel so that it works on older browsers.

**Comment by CentaurWarchief** [comment]
@spicyj actually there's only `import type` declarations, right? I mean, due the fact that fbjs doesn't understand import declarations or does?

I'm asking because I'm almost finishing a codemod which could be run with jscodeshift and convert all commonjs require calls to import statements. For example:

```JS
const Immutable = require('immutable')
const { OrderedMap } = Immutable;
```

Become:
```JS
import Immutable, { OrderedMap } from 'immutable';
```

I'm just finishing it to get rid of the default import specifier if there's no any reference to it in the file. In this case, my expected result is:
```JS
import { OrderedMap } from 'immutable';
```
I might run it in the current codebase and then submit a PR with such changes. What do you think?

P.S: Is not going to happen now, but very soon, just the time to wrap it all up and test more cases.

**Comment by spicyj** [comment]
@CentaurWarchief You're right. Right now our internal repo doesn't support import/export past "import type" for Flow's use. Since we keep this repo exactly in sync to make sure we're all using the same code, we won't be able to use that here until that happens at Facebook.
