### ISSUE TITLE
when edit a facebook note in Chinese, embed photos and videos will rerender/flash

### ISSUE THREAD

**Issue by xdclick** [facebook/draft-js#1078]
when I log in my facebook, and edit a note in Chinese,  embed photos and videos will rerender/flash wrongly。
and I encountered the same problem with my editor built on draftjs.

1. for a new line,  and write down the first character in Chinese,
2. or when I set the current style with bold/italic, and then type in Chinese, then the  embed photos, videos flash all the times.

**Comment by phucvuong159** [comment]
I have same problem. Are there any solution to resolve ?

**Comment by flarnie** [comment]
I'd like to start looking into this bug - just wondering what browser(s) you are seeing this in?

**Comment by flarnie** [comment]
I verified that this is still happening in Notes:
In Chrome when you enter an IME composition, images in the note will flash briefly. It only happens the first time for me - subsequent compositions don't seem to cause the flash. I was testing Katana and 2-set Korean because I'm more familiar with those, and it's likely a problem with IME and "composition mode", not just Chinese.

![shorter_gif_chrome_images_flash_when_ime_commits](https://user-images.githubusercontent.com/1114467/31959630-17685368-b8aa-11e7-86e4-8e7ddece17c3.gif)


The problem is worse in Firefox:
In Firefox every time I commit an IME composition it scrolls to the top of the note. Very annoying. Will add more details about that in a minute.

**Comment by flarnie** [comment]
In the gif above you can't really see the image flash - it's really fast, so I guess the video didn't catch it. But it does flash right as the composition is completed.

**Comment by flarnie** [comment]
I would not bother to fix the Chrome bug right now, but the Firefox one is really troubling.

If and only if the note includes an image, then finishing a composition will (most of the time) jump the focus/selection to the image. I was able to reproduce this easily.

**Comment by flarnie** [comment]
I was unable to reproduce this in the Draft.js 'media' example here: 
https://github.com/facebook/draft-js/tree/master/examples/draft-0-10-0/media

This is a bad bug but I only see it in Facebook's 'Notes' product. I'll file a bug for us internall to work on. If you could provide an example of how you were reproducing this in your application, that would be helpful, but for now I'm considering this a Notes product bug.

**Comment by blackChef** [comment]
@flarnie 
The problem is that if you typing using ime at the beginning of a block, draft-js will do a full rerender. Which is done by changing `react key` of the `DraftEditor` component. 
See code [here](https://github.com/facebook/draft-js/blob/master/src/component/handlers/composition/DraftEditorCompositionHandler.js#L124) and [here](https://github.com/facebook/draft-js/blob/master/src/component/base/DraftEditor.react.js#L422).
If we change the key of a react component, the component it self will not remount, but any children inside this component will do. Their `componentWillMount` and `componentDidMount` life cycle callbacks will be called again, which may cause "reload" or "flash" issues.
I manage to fix this by rerender `DraftEditorBlock` instead. When `restoreEditorDOM` is called, `DraftEditor` notifies `DraftEditorBlock` inside it to do an "update-key-rerender". The notify part can be done by creating a simple event emitter inside `DraftEditor`.
