### ISSUE TITLE
Pasting image with data URL source

### ISSUE THREAD

**Issue by erykpiast** [facebook/draft-js#1101]
**Do you want to request a *feature* or report a *bug*?** It's hard to say, I'd say missing feature or not handled case.

**What is the current behavior?** When image with `data:` URL is pasted to the editor, that huge, meaningless (for the user) blob of text becomes a content of newly created block. I cannot say it's not expected behavior (it does make sense for regular URLs, usually not so long and much more readable), but for big images (or even not so big, like 800 x 600 JPG) it causes very poor performance because of amount of data to process. 65K long `string` itself is shared under the hood, so that's not a problem, but `CharacterList` of such length may be. As result of that, editor freezes for a moment when image is pasted. Look at example here: https://jsfiddle.net/erykpiast/jwsdokwz/

Once I altered [this line](https://github.com/facebook/draft-js/blob/master/src/model/encoding/convertFromHTMLToContentBlocks.js#L408)  to `node.textContent = '_'` (it cannot be empty or white-space only for some reason), there is no slow down experienced.

**What is the expected behavior?** I'm not sure. There may be naive check for `data:` URLs, so in such case node text content is set to something like `data:image/jpeg;base64`, not a full URL. For "regular" URLs behavior may stay as it is now. Do you think it'd be breaking change that cannot be introduced as a patch?

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?** Draft 0.10.0, any browser. It's a "bug" introduced in v0.10 as previous versions didn't care about pasted images.

**Comment by hellendag** [comment]
Ha, we definitely shouldn't be treating `data` as the text content fallback.

You've got the right idea here -- we should use some dummy placeholder in the `data` case.

A PR would be welcome! :)

**Comment by erykpiast** [comment]
Hi @hellendag, thank you for your response! I'll make the PR with pleasure.

I just want to discuss some details beforehand. What do you think, what pattern is enough to check: `data:*` (like `if (url.startsWith('data:')) { ... }`) or something more specific like `/^data:\w+\/\w+;*/`? I'd say it shouldn't be too specific, on the other hand I can imagine there is thousands of people using the library in many different ways, so it may be one relies on value of the first kind (let's say `data:myCustomFormat`) and too general pattern will break her code. And well,  premature generalisation is just dangerous thing.

The second thing, what should be pasted instead of full URL? I'd say `data:MIME_TYPE` may be still quite poorly chosen default from UX point of view, I have no better idea though. I guess we'd like to avoid arbitrary strings like "Inline image" (maybe not exactly this, what even "inline" means to non-technical people), even if it may be the most readable and understandable thing we might ever do.

**Comment by flarnie** [comment]
Hi again @erykpiast - thanks for reporting this issue.

**tldr;** either `url.startsWith('data:')` or `/^data:\w+\/\w+;*/` would be fine, and I'd actually prefer we stop setting text content in the node at all. I would +1 any of those options if you still want to make a PR. :)

**More details:** I was working with the folks who added `img` support and the main use case we were considering was an editor that has a decorator implemented for `img` entity types. Looking at other text editor programs, the only example I found that does not support copy-pasting images is `quip`, and in that case if you try to paste an image it outputs nothing. You don't get the image url. I think that is the more expected behavior - it seems a bit weird from a UX perspective for the image url to show up.

@tylercraft please chime in if you have strong reasons for preferring we paste the image url. But it seems to me the simplest thing is to skip setting the node text content at all.

**Comment by flarnie** [comment]
It sounds like @aadsm might pick this up - heads up in case anyone else was looking at working on it.

**Comment by flarnie** [comment]
Thanks again for fixing this @aadsm !
