### ISSUE TITLE
Latest merge missing in version 0.10.0

### ISSUE THREAD

**Issue by gauravksoni** [facebook/draft-js#1115]
**Current version missing fixes related to *Initial fix for text insertion bugs in Android 5.1 #1033*.**

please update the version.

**Comment by flarnie** [comment]
Hi @gauravksoni - if I'm understanding this issue correctly, it calls out the fact that the latest PRs landed have not been released yet. We will be releasing a patch version with the latest changes soon - thanks for your patience. Closing this for now since we are actively working on getting a stable branch prepared to release.

**Comment by gauravksoni** [comment]
can you lemme know how long it will take to release latest version with all fixes?
