### ISSUE TITLE
Draft skips re render if the cursor position doesn't change

### ISSUE THREAD

**Issue by Revln9** [facebook/draft-js#1136]
**Do you want to request a *feature* or report a *bug*?**

Bug i think , not sure yet 

**What is the current behavior?**

check the fiddle , it's a  basic mention plugin that can display mutliple lists  and a draft editor written all in one file , try '#' and '@' to see it working , however when you add a trigger key '#' or '@' with a function ( `addText` in the fiddle ) the list will not display unless you change the cursor position and bring it back (left arrow , right arrow)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

http://jsfiddle.net/kcaewmw0/2/

**What is the expected behavior?**
show the mention list when a trigger key is added either by typing or by calling an insertText function.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

0.8 , 0.9

forcing draft js to update via `forceSelection()` isn't working either . if someone can help please, i'll be truly grateful.

**Comment by mmmoussa** [comment]
The issue you are having is not a bug with Draft.js. Your logic for showing the typeahead is being triggered from onChange. As a result, the typeahead correctly appears when a user types a trigger character, but it does not appear when your addText method inserts a trigger character since that insertion (correctly) does not cause onChange to fire. The reason why changing the cursor position away and back causes your typeahead to appear is that moving the cursor is a user's action and so does trigger onChange. In order to get the typeahead to appear after you insert a trigger key, you need to execute your typeahead logic yourself instead of expecting onChange to execute it.

If you want to quickly see this in effect, add `ref="editor"` to your TypeaheadEditor component and then add `this.refs.editor.onChange(this.state.editorState);` within your setTimeout right after you call addText.

**Comment by Revln9** [comment]
Hi mohamed , thank you for taking time to review and help ! i really appreciate ,  you've also enlighten us a bit more about the draft behaviour ,  assumptions are bad , really bad...
