### ISSUE TITLE
ContentState.createEntity Documentation Error

### ISSUE THREAD

**Issue by hnordt** [facebook/draft-js#1142]
Hello.

In `ContentState.createEntity` docs we have:

![image](https://cloud.githubusercontent.com/assets/1625399/25055714/e37d1932-213a-11e7-9f0d-e1ec0c7289d2.png)

It says "Returns new `ContentState` record **_updated to include the newly created DraftEntity record in it's EntityMap_**.".

Now in `ContentState.createEntity` source code, we have:

```typescript
  createEntity(
    type: DraftEntityType,
    mutability: DraftEntityMutability,
    data?: Object,
  ): ContentState {
    // TODO: update this when we fully remove DraftEntity
    DraftEntity.__create(
      type,
      mutability,
      data,
    );
    return this;
  }
```

Either the docs needs to be fixed or `ContentState.createEntity` should apply the created entity (atm it's just creating).

Actually `ContentState.createEntity` behavior is a bit strange, e.g.:

```js
      const contentState = editorState.getCurrentContent();
      const selectionState = editorState.getSelection();
      const contentStateWithEntity = contentState.createEntity(
        "LINK",
        "MUTABLE",
        { url }
      );
      const entityKey = contentStateWithEntity.getLastCreatedEntityKey();
      const contentStateWithLink = Modifier.applyEntity(
        // contentState doesn't has the created entity, but still applied the created
        // entity successfully
        // I think it happens because the entity is owned by the editorState currently
        // Reading the docs, I expected that only contentStateWithEntity
        // would be able to apply the created entity
        contentState,
        selectionState,
        entityKey
      );
      const editorStateWithLink = EditorState.push(
        editorState,
        contentStateWithLink,
        "apply-entity"
      );
```

**Comment by mmmoussa** [comment]
An instance of `ContentState` can contain an entity in its entity map without the entity being applied to any text. When using a new entity you have to create it and then apply it. The docs are describing this correctly. `ContentState.createEntity` should not apply the created entity.

With regard to your example about the strange behaviour, the reason you can use `contentState` is because your comment that it doesn't have the created entity is incorrect. `contentState.createEntity` returns the same instance of the `ContentState`, which means that both `contentState` and `contentStateWithEntity` are the same.

**Comment by hnordt** [comment]
@mmmoussa thank you, I understand now. The source of my misunderstanding was the "Returns new `ContentState`". I fixed it: https://github.com/facebook/draft-js/pull/1150

Btw, as `ContentState.createEntity` creates a new entity inside the current instance and returns it, it looks a bit like a mutable operation, no?

```js
      const contentState = editorState.getCurrentContent();
      // As Draft.js uses an immutable modal, I expect that only contentStateWithEntity
      // contains the newly created entity
      const contentStateWithEntity = contentState.createEntity(
        "LINK",
        "MUTABLE",
        { url }
      );
```

**Comment by flarnie** [comment]
Thanks for the link and the context - that helps.

This change does make the docs more clear @mmmoussa - thanks for updating this.

This will work differently once we fully deprecate the old Entity API. But for now I don't think the docs should get into that, so this is good.

If you're interested in more context:
In v0.11.0 the `contentState.createEntity` method will actually return a new instance of contentState. Because:
`contentState.createEntity` will call `createEntityInContentState` - https://github.com/facebook/draft-js/blob/0.11.0-alpha/src/model/immutable/ContentState.js#L138-L144
Which calls `addEntityToContentState` https://github.com/facebook/draft-js/blob/47c26cc778da654231df0808fcb9bb1d2052662d/src/model/transaction/addEntityToContentState.js#L25-L28
which calls `set` on the Immutable set, returning a new instance. https://facebook.github.io/immutable-js/docs/#/Map/set
