### ISSUE TITLE
List item depths limited to 4

### ISSUE THREAD

**Issue by zachberry** [facebook/draft-js#122]
As far as I understand this is currently a hardcoded limitation as the indents for lists utilize margins applied via css classes like `public/DraftStyleDefault/depth0`, `public/DraftStyleDefault/depth1`, etc. However these only go up to depth4. After that list items are aligned to the far left.

![screenshot 2016-02-29 15 54 14](https://cloud.githubusercontent.com/assets/73479/13408639/e05c3958-defc-11e5-8048-e15a41af2bdd.png)

**Comment by hellendag** [comment]
If you need more depth for your use case, you can add CSS rules alongside https://github.com/facebook/draft-js/blob/master/src/component/utils/DraftStyleDefault.css. There are some comments in that CSS file to that effect.

I didn't include more depth values because I didn't want to bloat the CSS beyond a simple use case. :)

For the screenshot, did you add more depth using <kbd>tab</kbd>, or via paste? Hopefully we're guarding against going beyond level 4 for tab behavior, but it looks like there's a bug somewhere.

**Comment by zachberry** [comment]
Ah, cool - Didn't see the comment regarding blockStyleFn. If it's possible then it's not that big of an issue.

I tweaked the rich.html example to add in a button to increase the depth (Depth++) of the selected list item, which is how I was able to take the screenshot. So I don't think you have a bug here.

**Comment by hellendag** [comment]
Cool, thanks. :) Let me know if you run into any issues with styling depth beyond the default levels.
