### ISSUE TITLE
Is there somebody working on splitting content into columns or pages using draft.js' output?

### ISSUE THREAD

**Issue by sarawinter** [facebook/draft-js#1222]
**Do you want to request a *feature* or report a *bug*?**

This is possibly a contact request?

Both myself and a friend of mine have run into this issue (on different projects, in different companies) where the project requires that we split output into columns or pages (for print), and we are both using draft.js for the source content.

I do not expect this to be built into draft.js as a feature since it is a bit out of scope, but I have been trying to find out if there is somebody already working on a solution for this.

In jQuery there is [Columnizer](https://github.com/adamwulf/Columnizer-jQuery-Plugin), which does the job fairly well, but I have not been able to find a react equivalent.

Do you know of any projects that have solved this, or that are working on a solution, or that are willing to collaborate?

If not, is there some place where I could get some pointers or support for creating my own project to solve this issue?

**Comment by jan4984** [comment]
I suggest to use multiple draftjs editors, one Editor for one column

**Comment by confiks** [comment]
Splitting the text up manually in columns can be a solution, and for example the [Ory editor](https://github.com/ory/editor) implements a column layout with separate editor instance (and with Slate instead of DraftJS). 

On the other hand, I'm not entirely sure manually splitting is really the solution for designing long form articles. There, the content is mostly linear, with perhaps a few asides and images. Fundamentally this is about text reflow in the context of different screen sizes and in print.

I'm myself trying to see if simply applying CSS to block level DraftJS elements (i.e. `float: right` inside media rules) is enough to get to acceptable article layouts for all screen sizes. For splitting up text in columns specifically, you might want to try the [CSS3 multicolumn layout rule](https://caniuse.com/#feat=multicolumn), for example [like this](https://stackoverflow.com/questions/24871693/bootstrap-writing-in-columns-like-a-newspaper?answertab=votes#tab-top). 

I don't know if it suffices (and is compatible in all browser), but I guess that rule wasn't around when the jQuery Columnizer plugin was released. Additionally, you could get the DraftJS HTML out of React and do the jQuery transformation just for print.

**Comment by paloobi** [comment]
Hope this discussion was helpful. I'm closing the issue, as it doesn't seem to include any bug/feature request for Draft, but feel free to continue the discussion.
