### ISSUE TITLE
block-level metadata

### ISSUE THREAD

**Issue by angelf** [facebook/draft-js#129]
What is the right way to add meta-data at the block level? Our current use case is to allow editing the anchor name and section number for each header. I've played around with some options but no one seems quite right:
1. Creating an entity to represent the block level metadata. This would seem to be the "draft-way" of doing this, but since it's not possible to create entity ranges of zero length, this means I've got either to insert a dummy character, or 'spend' a character to represent this entity, which is not cool since the first character of the block may actually be linked to some other entity. 
2. Extending ContentBlock with a custom field. Doesn't seem really possible since ContentBlock  is tied to an Immutable Record and Records are closed to new fields. 
3. Storing the block-level metadata out of band. This is possible but I'd like all state to be reflected on the ContentState object so undos, convertToRaw, etc. will work as expected. 

Does it make sense to add a `data` attribute to ContentBlock? We already have `depth` so it's clear that some block-level data is sometimes needed, but the current mechanism is not extensible.

**Comment by hellendag** [comment]
Option 1 is the way this is currently done. If you are aiming to have a block-level entity, the assumption is that you aren't trying to apply entities to any of the characters within it. Thus the dummy character with an entity applied to it would be sufficient. Are you finding that you need to have block-level data *and* character-level data within the same block?

I know it's an awkward API, and I definitely would like to improve it.

What I have been thinking about is creating a record like `EntityBlock` that would be a sibling of `ContentBlock`, and would provide exactly this behavior. The challenge is making sure that these blocks are handled appropriately while operating on the `blockMap` during modifier and transaction functions. I believe it's doable, it just requires time to make it work well.

**Comment by angelf** [comment]
> Are you finding that you need to have block-level data and character-level data within the same block?

Yes, that's the case. What I want is to give a way to "name" any block (a header, a list item, a normal paragraph, etc.), so it can be linked directly. Since it's a regular block it will in many cases have links or other entities _inside_ the content.  

I guess there are many other use cases for this kind of stuff, for example: to mark a block as problematic (needs review), to add comments to it, to set block-level formatting (margins, borders, alignment, list style type, background, etc.), and so on. 

I for example have also another use case in which we allow editors to create new revisions for parts of a document. Essentially they can say.. "after date X the right content for this block is going to be". It would be convenient to express this as a property of the block as a whole.  

I'd be happy to make a pull request with the changes to introduce the a data attribute to ContentBlock record if it has any chances to go in. It's a small change really.

**Comment by hellendag** [comment]
Very interesting ideas.

FWIW, for block-level CSS formatting, if it's based purely on the `ContentBlock` but still uses default block rendering, you can generally use `blockStyleFn`.

I'd love to see a PR for this. It's simple enough to add to `ContentBlock`, but you'll want to make very sure that `Modifier` and transaction functions can all cope well with the new value, especially when it comes to behavior like range deletion. I think this value could make use of the `Entity` store and API, so that individual blocks only need to track key references.

**Comment by noizex** [comment]
Hmm, somehow I assumed (haven't yet digged into Draft.js much) that block metadata is something that exists :) Now after checking the TeX example I understand how rich text custom blocks work. 

I really like angelf's idea. Wouldn't it actually be better to use something like a block with metadata instead of using block with placeholder character and refer to some data in entityMap even for things like that TeX example (assuming we want separate block with TeX, otherwise we need inline capabilities)? Like video block - it doesn't need any special formatting or benefits of entities, it's just a chunk of content to be generated based on metadata tied to the block. Same for basically any non-inline rich text element.

**Comment by angelf** [comment]
@hellendag Ok, so let's do it using the Entity store. 

One thing I don't quite like about Entities is that they are not part of the ContentState, so undos won't work as expected and they make all the components not pure. But I guess this is better addressed as a separate issue.

**Comment by corbanbrook** [comment]
I have a similar use case, allowing inserting of oembeds. Having trouble finding out how to attach the oembed data to my custom block component.

![screen shot 2016-03-03 at 11 25 52 am](https://cloud.githubusercontent.com/assets/62406/13500963/bf0f0428-e132-11e5-8518-d95a608622f9.png)

**Comment by hellendag** [comment]
> One thing I don't quite like about Entities is that they are not part of the ContentState, so undos won't work as expected and they make all the components not pure.

Yeah, I have also come to believe that entities should not be stored separately. It's a remnant of the pre-immutable version of the model, and I'd like to improve it.

> I have a similar use case, allowing inserting of oembeds. Having trouble finding out how to attach the oembed data to my custom block component.

@corbanbrook: You can apply the oembed data to an entity, and apply the resulting entity key to a dummy character in your block. Then in your custom block component, you can access it again via the `Entity` API. As noted above, it's not the prettiest API, and is worth improving. :)

**Comment by angelf** [comment]
This is the PR: https://github.com/facebook/draft-js/pull/157

The only transaction that seems to require updating is ``splitBlockInContentState``.

**Comment by thesunny** [comment]
In the PR comments, @hellendag suggested some Modifier methods.

Just reposting here to keep this issue updated.

May I also suggest:

- Updates to the documentation
- Modify `ordered-list-item` and `unordered-list-item` to use the new metadata instead of the only used in one place `block.getDepth()`. Seems like the perfect use case for the metadata.

**Comment by angelf** [comment]
Good, It'll take me a few days until I can repost the PR with the changes. Shall I update also the Tex examples to use block-level metadata?

I am not sure about moving `depth` to the entity store... right now Entity data modifications do not support undo so the change would break undo for indent/deindent actions.

**Comment by thesunny** [comment]
Ahh... that makes sense. I didn't think about undo behavior.

Feels like a definite +1 for moving Entity information into the state... I'm going to add a new issue related specifically to moving Entity information into the state.

**Comment by kaizen1** [comment]
I have a use case where block level content could have multiple data values (i.e. multiple key/values assigned at the block level e.g. not just a URL). Does this fix allow that? For example: author: Joe; workflow: approved;
Not a coder so please go easy on me ;)

**Comment by mkhazov** [comment]
block level metadata was implemented in #216 

Probably this issue should be closed.

**Comment by mitermayer** [comment]
This has been fixed on https://github.com/facebook/draft-js/pull/216
