### ISSUE TITLE
How to properly gather data for bug reports? Help needed!

### ISSUE THREAD

**Issue by neemah** [facebook/draft-js#1348]
First of all, great product guys, very good job, especially considering set of useful plugins.

Recently we replaced one of our textarea control with drafjs and now sentry register a bunch of errors we have no idea how to reproduce, typically it looks like this:

<img width="934" alt="screen shot 2017-08-24 at 13 55 52" src="https://user-images.githubusercontent.com/212695/29663475-faa3bbec-88d3-11e7-85b2-f3af9bb79ff5.png">

<img width="908" alt="screen shot 2017-08-24 at 13 56 40" src="https://user-images.githubusercontent.com/212695/29663504-17102c48-88d4-11e7-98a9-75fd40fd347f.png">

We can't get access to what our clients type in editor (it's private data), so we don't have repro steps to properly register new bugs.

Any thoughts on how to debug this errors to prepare proper bug reports?

Thanks in advance!

**Comment by flarnie** [comment]
This is a valid concern, and has been a pain point for us internally at FB. I'd be open to ideas/PRs to improve this, but tldr here is what we do at FB:
- Dogfooding gives us reports with more detail from employees, so that we can ask the person for more info, screenshots, etc.
- Automated logging of what browser/OS they are using, what url they were on, any other data that can be logged from outside of Draft.js
- Using an error boundary (https://facebook.github.io/react/blog/2017/07/26/error-handling-in-react-16.html#introducing-error-boundaries) to log Draft.js errors and capture the `EditorState` at that point.

We have also admittedly hacked in extra logging for errors that are especially hard to reproduce - [this is an example](https://github.com/facebook/draft-js/pull/1156). I would like to find a better approach though.

**Comment by jackyho112** [comment]
@flarnie 

Using error boundaries provided by React 16 seems to be a pretty reasonable way to do this, no?

**Comment by jackyho112** [comment]
Would it make sense to implement a React 16 error boundary to wrap around or at `DraftEditor` or `DraftContents` inside Draft.js and allow users to customize the error handling allowed by the boundary?

**Comment by jackyho112** [comment]
It probably makes sense to implement React 16's error boundary in some ways inside Draft.js?

**Comment by flarnie** [comment]
@jackyho112 I think allowing the user to wrap their Draft component inside the <ErrorBoundary> is the most flexible thing. The component with the error boundary logic only catches errors thrown from it's children, not from itself, so to catch errors in an <EditorComponent> implemented with Draft.js I would wrap it in something like https://github.com/bvaughn/react-error-boundary

**Comment by jackyho112** [comment]
To implement [react-error-boundary](https://github.com/bvaughn/react-error-boundary) in Draft.js, I guess we would use it to wrap the `DraftEditor` component?

**Comment by flarnie** [comment]
Thanks for chatting about this @jackyho112 - I wasn't really clear before. I think we should let users of Draft choose to wrap it in an `<ErrorBoundary>` using `react-error-boundary`, like so:
```
import ErrorBoundary from 'react-error-boundary';

const myErrorHandler = (error: Error, componentStack: string) => {
  // ... log this.state.editorState, the error, the componentStack, etc.
};

<ErrorBoundary onError={myErrorHandler}>
  <DraftEditor
    editorState={this.state.editorState}
    onChange={this.onChange}
    ref="editor"
   />
</ErrorBoundary>
```

I guess now that we have talked more, I don't know of any action items for this issue. We could reopen it if someone has a specific idea, but for now I would advise people to log the `editorState` and possibly the browser selection state using `react-error-boundary`. 

Selection state is a common place for bugs - you can also access the `selectionState` from the `EditorState` - see https://draftjs.org/docs/api-reference-selection-state.html#content, and then compare that to the browser selection state -  https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection

Thanks for drawing attention to this issue @jackyho112 - feel free to open a new issue if you have ideas for how to improve error logging with Draft. 🏗️✨

**Comment by jackyho112** [comment]
@flarnie 

I guess with React 16 or `react-error-boundary`, it is quite convenient and easy to catch any error from a Draft editor. It is simple to implement, too.

Would you like me to document it just so people are aware? I think letting people know of some examples to implement error handlings could be helpful. 

I am fine either way because implementing an error boundary should become obvious once React 16 is released officially and more widely used.
