### ISSUE TITLE
Will you relicense to MIT, like React did?

### ISSUE THREAD

**Issue by solsson** [facebook/draft-js#1417]
https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
https://github.com/facebook/react/commit/d63249d03488fec1ea92a81ba29f0e87a82feeae

**Comment by flarnie** [comment]
I will look into this and get an answer a soon as possible. Thanks for your patience while we figure this out.

**Comment by flarnie** [comment]
We are reconsidering our use of the BSD + Patents license, but we are not ready to make a change to this project yet. We are working with Facebook’s legal team to review our intellectual property in this area, but it will take some time. Unfortunately, we cannot commit to any certainty or timeframe for this change, but we will let you know as soon as that changes.

For now I'm closing this issue since there is nothing actionable and we don't know how long things will take. Sorry that there isn't more to report.

**Comment by jeffhoel** [comment]
Hi, I was wondering if there is any new status you could share about this.
Thanks, and have a great day!

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10180

**Comment by solsson** [comment]
🎉 #1967
