### ISSUE TITLE
ContentBlock auto generate CharacterList

### ISSUE THREAD

**Issue by camurai** [facebook/draft-js#1455]
**Do you want to request a *feature* or report a *bug*?**
Feature Request

**What is the current behavior?**
Currently when inserting a new ContentBlock into the ContentState, It appears that you need to generate the appropriate default CharacterList for the text set in the new block, otherwise the block text does not display. In order to work around this, I have used:
```js
convertFromRaw(convertToRaw(contentState))
```
as the convert back from Raw generates the CharacterList.

Here is a jsfiddle highlighting the problem. there is one line of code commented out that is my convertToRaw and back again work around:
https://jsfiddle.net/v7o1h76d/
Let me know if there is something else i should be doing to insert the block that would get around this problem.

**What is the expected behavior?**
Preferably the default CharacterList would be auto generated when the ContentBlock instance is first created as part of its constructor.

**Comment by mitermayer** [comment]
Hi @camurai,

Thanks for this feature request. To give a bit more context, the way a ContentBlock is render it requires each character of the block text to have a matching CharacterMetadata.

On your above example you are providing an initial text to the ContentBlock creating without supplying a characterList. The default value for ContentBlock.characterList record is of Immutable.List(), so that means if you change your example to supply and empty string `''` instead of `"blargh"` it will work as expected.

If you want to have blocks created with the string `"blargh"` you would have to build the characterList object, that could be done by creating an Immutable.List of CharacterMetadata.EMPTY that matches same length as initial string.

so for the object would look like:

```
new ContentBlock({
  key: newBlockKey,
  type: 'unstyled',
  type: 'unstyled',
  text: 'blargh',
  characterList: Immutable.List([
    CharacterMetadata.create(),
    CharacterMetadata.create(),
    CharacterMetadata.create(),
    CharacterMetadata.create(),
    CharacterMetadata.create(),
    CharacterMetadata.create(),
  ])
})
```

I have updated the your fiddle to show the above behaviour https://jsfiddle.net/v7o1h76d/2/ 

*** 

I also agree with you, we could do a better job on making easier to create ContentBlock, by  defaulting characterList to a List of **CharacterMetadata.EMPTY** that matches the size of the **text** passed.

**Comment by mitermayer** [comment]
Created a PR addressing this issue in here https://github.com/facebook/draft-js/pull/1472
