### ISSUE TITLE
getDirectionMap performance (large documents)

### ISSUE THREAD

**Issue by angelf** [facebook/draft-js#146]
I am investigating performance with large documents (thousands of blocks) which is a bit sluggish. The first thing I see is that every keystroke is triggering a call to `getDirectionMap`, which recalculates the direction for each node, and updates a map. The biggest overhead is on re-creating the OrderedMap (which most of the times is exactly the same as before)

<img width="424" alt="screen shot 2016-03-03 at 15 27 19" src="https://cloud.githubusercontent.com/assets/121845/13497412/72210df0-e155-11e5-8b85-c9f9f4287d59.png">

I am wondering if there is any way to avoid this memory allocation by only recalculating (and updating) the direction for blocks that have changed. Or to completely bypass this step if the editor has been initialized with textAligment. 

A similar situation is seen on `regenerateTreeForNewBlocks`. It ends with ends with a `prevTreeMap.merge(changed);`, but on most of the edits a single block has changed, so it'd be most efficient to just do a .set()

**Comment by hellendag** [comment]
Curious -- how many thousands of blocks are you testing with?

This issue might be similar to what we're seeing in #63. Can you provide the profile file? I'd like to investigate it. I wouldn't expect it to be so expensive to perform these kinds of operations, so there may be a perf bottleneck within immutable-js.

`OrderedMap` is also known to be a bit expensive, so I'm sure `EditorBidiService.getDirectionMap` could be optimized, too. In most cases, of course, block direction won't change at all. We should probably only update direction for blocks that have changed, then continue looking until we find an unchanged direction. (Since `UnicodeBidiService` uses the direction of the previous block to determine direction of otherwise neutral blocks.) When we find an unchanged direction, we're done. The results can then be applied.

Regarding `regenerateTreeForNewBlocks`, we should actually only be generating new tree maps for changed `ContentBlock` objects, so I don't think it's quite the same. And I'm not sure whether using `merge` should be a problem there instead of `set`, as I don't expect them to have totally different perf profiles under the hood. That said, if you're seeing perf issues there, then there's something there to solve. :) Do you have a profile for this too?

**Comment by angelf** [comment]
It is indeed a pretty monstrous document (7025 blocks). I've uploaded the CPU Profile to https://s3.amazonaws.com/vlex-interchange/getDirectionMap.cpuprofile

This is within a larger app so some of the stuff is really our fault, but I am pretty sure the getDirectionMap lag is not caused by us.  

On the profile you'll find both the `getDirectionMap` and the merge called from  `regenerateTreeForNewBlocks`. The merge is a much lesser issue but still 6ms for each keystroke is not optimal. I did test and for a single-modification `set` is faster (I don't know much about Immutablejs but it seems that `merge` goes over withMutations which makes a temporary copy of the map) 

![image](https://cloud.githubusercontent.com/assets/121845/13503579/6359cad0-e170-11e5-82fb-c22c641dae0a.png)

**Comment by hellendag** [comment]
> This is within a larger app so some of the stuff is really our fault, but I am pretty sure the getDirectionMap lag is not caused by us.

Yeah, I agree. This looks like it could be significantly tightened up within `EditorBidiService`.

> I did test and for a single-modification set is faster (I don't know much about Immutablejs but it seems that merge goes over withMutations which makes a temporary copy of the map)

Probably worth a jsperf test to verify, but this sounds like a worthwhile optimization.

Separately, I also notice that a lot of time is spent in `React.createElement`, and this is another area where there could be perf wins. Most notably, `DraftEditorContents` currently has to create block elements even if `DraftEditorBlock` will bail out in `shouldComponentUpdate`. There is room for improvement here.

**Comment by angelf** [comment]
Yep, this is the jsperf I used
http://jsperf.com/immutable-js-maps

**Comment by hellendag** [comment]
Nice, thanks! Pure win. Want to send over a PR?

I bet there are a bunch of places that I used `merge` that could benefit from this...

**Comment by angelf** [comment]
I did a little work on the .merge part and I am not getting much of a gain. I guess what the Profile is really showing is not the cost of merging but the cost of materializing the lazy sequence. 

This is my attempt to tackle the getDirection issue according to the logic you described:
https://github.com/facebook/draft-js/pull/156

Experimentally it works well (it does reduce the time) & the tests pass, but I think I am going to need some adult supervision on the correctness.

**Comment by lacker** [comment]
It seems like this direction is valid for investigation but the issue has gone quiet so it's not really providing value to us. I'm going to close the issue but please feel free to open a new one if you have a new issue to report.
