### ISSUE TITLE
Entity state lost when merging blocks.

### ISSUE THREAD

**Issue by ZhengRaymond** [facebook/draft-js#1503]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a entity's block changes. For example, suppose a user merged two blocks; then entities within the block2 would have their parent block changed from block2 to block1. This causes the entities to be entirely recreated, resetting the entity state. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create 2 blocks, with a entity in the 2nd block. In the entity's constructor, set `this.state={ counter: 0 }`, and in the constructor,  `setInterval(() => console.log(this.state.counter); this.setState({ counter: this.state.counter + 1}), 1000);`.

When the entity is rendered, it will print 0, 1, 2, 3.... etc. After joining the two blocks (backspace at the beginning of 2nd block), the entity will be recreated. The original state of the entity now causes errors, and the new state restarts its counter from 0, 1, 2, 3.... 

**What is the expected behavior?**
I think the state of the same entity should be preserved regardless of where the entity is moved. As long as the user is viewing the same entity, that same entity should retain its state.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Tested on (although pretty sure this is independent of browser/OS):
Draft.js version: 0.10.0
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)
OS: MacOS Sierra Version 10.12.6

**Comment by juliankrispel** [comment]
@ZhengRaymond thanks for reaching out! As far as I can see you're talking about Decorator components (which can represent an entity). The component will be rerendered because it's moved to a completely different position in the tree. That's do with how react renders the component tree and has little to do with draft.js.

If you want to persist this state I'd recommend you manage it outside of the component lifecycle. For example with redux.

Also btw - please join the draft js community on slack for more immediate help: https://draftjs.herokuapp.com
