### ISSUE TITLE
No cursor/caret when no text 

### ISSUE THREAD

**Issue by dilizarov** [facebook/draft-js#1535]
Long story short, for some reason with my implementation there is no cursor/caret when there is no text. the customStyleMap applies styles to a span and when this same span has the styles: `display: inline-block` and `min-width: 1px` I see the cursor/caret.

I don't think this is a bug with Draft JS. I think this is something in my codebase. When I use customStyleMap, I can only get styles applied when some text is written, but I see the cursor at that point anyways, and it defeats the purpose. Is there anyway to get my styling needs onto the span when there is no text in the Editor?

**Comment by thibaudcolas** [comment]
Hey @dilizarov, I would hope there is a simpler fix (like not using spans?) but here is something you could try:

- Use the [`:empty` CSS selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:empty) to add your style overrides.
- Test for "no text" with something like `block.getText().length === 0`.

**Comment by juliankrispel** [comment]
Hello @dilizarov please provide a way to reproduce this problem and maybe we can help, you can use codesandbox.io for this.

Also btw - please join the draft js community on slack for more immediate help: https://draftjs.herokuapp.com

I'm causing this since as you suggested it isn't really an issue with draft.js. If you can provide an example that suggests optherwise, let's reopen.

Thanks for reaching out!

**Comment by sirushtisri** [comment]
I have same problem with my environment! Did you get any solution @dilizarov ???
