### ISSUE TITLE
Global key bindings

### ISSUE THREAD

**Issue by miickel** [facebook/draft-js#1549]
I'm building an app that defines some global hotkeys unrelated to the draft.js editor. If draft.js is focused, none of my key binding handlers trigger. I understand this is because draft.js has its own pipeline for handling key bindings and swallows all key presses.

Is there a way to say "Hey draft.js, I've got a key handler outside that'll take care of CTRL+K, please just ignore and leave it to me"? I've tried using `handleKeyCommand` and returning 'handled' - this works to disable the key binding in draft.js but it won't trigger my handler outside of draft.js.

I'm binding my keys using mousetrap.js, if that matters.

One solution would be to use a custom `keyBindingFn`, but that would require me to define all my hotkeys twice.

**Comment by juliankrispel** [comment]
@miickel I'm afraid draft.js needs to take control and cancel key commands to control the default `contentEditable` behaviour and there is no way to just `turn it off` - it's unlikely that a feature like that would be added.

What I'd recommend is this:

Separate your event handlers from your event listeners, `keyBindingFn` dispatches a synthetic event which is pretty much the same as a standard browser event, so you should be able to reuse the same event handlers that you use with mousetrap.

Also btw - please join the draft js community on slack for more immediate help: https://draftjs.herokuapp.com

You can ping me directly on there as well.

I'm going to close this since it's not really a bug or a feature request for draft.js

Thanks again for reaching out!

**Comment by DaniGuardiola** [comment]
Hi! Sorry for reopening an old issue, but I'm having the same issue. In my case, re-mapping the handlers is a rather messy approach, so I ended up with a hacky buy cleaner (if you disregard the hack itself) way of working around this which is manually triggering key events in the document element inside the draft-js handler.

Draft-js expects a 'handled' or 'not-handled' string as return value, I think it'd be great if we could return a third string (maybe 'propagate'?) that explicitly declares the intention to draft-js, so that it can disregard the event without doing a `preventDefault()`.

How does that sound? It is opt-in, so it shouldn't make it too easy to break stuff up. Of course, some native `contenteditable` could potentially break it, but with a clear warning in the documentation about this it should be fine for developers.

This would make my life way easier. Thank you!
