### ISSUE TITLE
Heads up: Chrome 65 will change composition events on Android

### ISSUE THREAD

**Issue by javan** [facebook/draft-js#1657]
See the following issues for details and please chime in if you have anything to add.
- https://bugs.chromium.org/p/chromium/issues/detail?id=764439#c9
- https://bugs.chromium.org/p/chromium/issues/detail?id=812674

**Comment by flarnie** [comment]
Thanks for posting this @javan - I'll leave it open for a little while for visibility.

So far we have been 100% blocked from supporting Android web on Draft.js due to the lack of consistency with other browsers and with the spec in how events are handled, so this doesn't make things worse for Draft.js per say. But we have continued to look for opportunities to add better support for mobile, and this is relevant to that effort.

**Comment by javan** [comment]
> So far we have been 100% blocked from supporting Android web on Draft.js due to the lack of consistency with other browsers and with the spec in how events are handled

I feel your pain!

> so this doesn't make things worse for Draft.js per say

It appears it does make things worse since composition events are now dispatched when moving the cursor.

Here's draft on Chrome 65 beta. This problem doesn't occur on Chrome 64.

![draft-chrome-65-beta](https://user-images.githubusercontent.com/5355/36433859-91ed4268-162b-11e8-8846-1e215a289153.gif)

**Comment by flarnie** [comment]
!!! Thanks for flagging this. Will look into it later today.

**Comment by flarnie** [comment]
@javan can you give repro steps for that bug you showed? We haven't had luck reproducing it using chrome canary, which is version 66.

**Comment by javan** [comment]
Gotcha. In case it helps, I posted steps and a video comparing Chrome 64 and 65 on Android here: https://bugs.chromium.org/p/chromium/issues/detail?id=812674#c23

It’s practically unusable on 65 once you move the cursor.

**Comment by flarnie** [comment]
Merging this into a general Android bug issue - see https://github.com/facebook/draft-js/issues/1895
