### ISSUE TITLE
convertFromRaw requires at least one block

### ISSUE THREAD

**Issue by ctbarna** [facebook/draft-js#1660]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
```
convertFromRaw({
  "blocks": [],
  "entityMap": []
})
```
Running the above code throws a new exception in 0.10.5 because the [duck-typing for tree nodes](https://github.com/facebook/draft-js/blob/07eb9c4e2e2771d284c3c8f0c0d78d6b488619fd/src/model/encoding/convertFromRawToDraftState.js#L217) assumes there is at least one block. Previously, `convertFromRaw` would not throw an error and just return an empty content state.

**What is the expected behavior?**
The current functionality might be expected behavior but it seems odd that it throws because of a feature flag.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
0.10.5 (It looks like it was first introduced in 93df36d1cd2799)

**Comment by shivavelingker** [comment]
Has there been any update on this?

**Comment by ermanolca** [comment]
is there any progress on this issue?

**Comment by mrkev** [comment]
This should be fixed, since the check no longer assumes there's at least one block.

Before:

https://github.com/facebook/draft-js/blob/07eb9c4e2e2771d284c3c8f0c0d78d6b488619fd/src/model/encoding/convertFromRawToDraftState.js#L217

Now:

https://github.com/facebook/draft-js/blob/db3216d9e2b35d976be5a56c69e680f7dcf714e1/src/model/encoding/convertFromRawToDraftState.js#L216-L218
