### ISSUE TITLE
Fix default Selection behaviour after initialising the EditorState 

### ISSUE THREAD

**Issue by nikgraf** [facebook/draft-js#172]
Would be great to mimic the default `<textarea>` behaviour where the Selection is placed at the end in case you click somewhere further down the the last text after initialising the editor with content. Right now the Selection will be at the beginning.

I was wondering if this should be part of these two static functions: https://facebook.github.io/draft-js/docs/api-reference-content-state.html#static-methods

We already do this in the draft-js-plugin editor:
https://github.com/nikgraf/draft-js-plugin-editor/blob/6b1da3af452780120322ebcde0f4863f320fb406/src/pluginEditor/utils/forceSelectionToLastCharacter.js

**Comment by nikgraf** [comment]
Happy to create a PR in case this is desired behaviour …

**Comment by spicyj** [comment]
Doesn't this happen already as long as the .public-DraftEditor-content is tall enough? Check the demo on the draft-js homepage.

**Comment by hellendag** [comment]
Looks like I didn't include it in the documentation, but: https://github.com/facebook/draft-js/blob/master/src/model/immutable/EditorState.js#L318

**Comment by nikgraf** [comment]
Ah nice, nevertheless is there any reason not to make this default behaviour for `createFromBlockArray` & `createFromText `.

**Comment by hellendag** [comment]
Not sure if this is what you're suggesting, but we can't make this the default `SelectionState` for an `EditorState` object since we don't know whether the initialized editor actually has focus.

I'm not totally sure what the bug case is here. In what case is the selection at the beginning on focus?

**Comment by hellendag** [comment]
Going to go ahead and close this one, given the discussion on Slack.

I think the conclusion here is that rather than giving the container clickable padding, the `public-DraftEditor-content` element should have it.

Short of mapping the click x/y coordinates to a text coordinate in the editor (which I'd rather not do :smiley:) I think that this is the right solution.
