### ISSUE TITLE
Editor doesn't go to a next line and loose first input character when trying to customize 'unstyled' block

### ISSUE THREAD

**Issue by grundiss** [facebook/draft-js#1776]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Editor doesn't return caret and loose first input character when trying to customize 'unstyled' block
https://jsfiddle.net/b7u189tp/1/
![draftjs](https://user-images.githubusercontent.com/2481018/40712319-0ef87de0-6406-11e8-8aed-ac54822e70cc.gif)

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
^0.10.5

**Comment by grundiss** [comment]
+ it doesn't do 'backspace'

**Comment by grundiss** [comment]
The workaround I found is quite dirty, but it works
```javascript
import DraftEditorBlock from "draft-js/lib/DraftEditorBlock.react";

function UnstyledComponent(props: Object) {
  return (
    <div data-custom="yep">
      <DraftEditorBlock {...props} />
    </div>
  );
}
```

I'm pretty sure it is not the official way to do that.

**Comment by andrewbranch** [comment]
@grundiss I may be misunderstanding, but it sounds like what you want is [`blockRenderMap`](https://draftjs.org/docs/advanced-topics-custom-block-render-map.html) rather than `blockRenderFn`. If I understand correctly, the former is for adding a custom wrapper around a ContentBlock with normal Draft JS-handled editing behavior, and the latter is for rendering components with entirely separate interactions not handled by Draft itself within a Draft editor, e.g. images or media players.

(This does beg the question of what exactly `editable: true` is for in `blockRenderFn`—I don’t really understand that, but I think at least your case is a prime candidate for `blockRenderMap`.)

**Comment by grundiss** [comment]
From my perspective `blockRenderMap` and `blockRenderFn` do pretty much the same job. Map is easier to write and maintain, but function gives you more control.

**Comment by niveditc** [comment]
I think `blockRenderMap` is probably the way to go here. Closing the issue & feel free to reopen if you feel that it needs further discussion.
