### ISSUE TITLE
How to handle backspace in a custom block

### ISSUE THREAD

**Issue by remko** [facebook/draft-js#181]
I have a custom block renderer component that looks like this:

```
const Section = ({block, offsetKey}) => {
  const { text } = block;
  return <div data-block={true} data-offset-key={offsetKey}>{text}</div>;
};
```

Editing text in this seems to work fine, but hitting 'backspace' resets the selection to the beginning of the block, no matter where the cursor was. Am I missing something such that the component behaves properly on edits? Or is editing in a custom component not supported?

**Comment by hellendag** [comment]
You should compose a `DraftEditorBlock` within your custom block if you'd like to render the text for the block. That way, the editor can use the rendered DOM to track selection behavior properly.

We hadn't used this behavior yet internally, so I overlooked it. It needs to be documented better. :)

**Comment by remko** [comment]
Thanks. Making it a DraftEditorBlock indeed makes the selection behave properly, but the thing is that I wanted to avoid it rendering inline styles in this custom block. Is there a way to get proper edit behavior without having it decorate the inline styles?

**Comment by hellendag** [comment]
Oh, interesting.

In order to map DOM selection to the model, the DOM structure must match the model. Which means that the decorators and leaf elements within the block need to be present. Moreover, the `DraftEditorLeaf` is responsible for setting DOM selection within itself. So if you aren't using that component, you'd have to implement that yourself.

Can you tell me more about this use case? I certainly don't want to say that it can't be done -- ideally we can come up with a good solution here, or define an API that helps support use cases like these. :)

**Comment by remko** [comment]
In my case, I have blocks of text where styles don't make any sense. I don't want to actually delete the styles when converting to this block, I just want to pretend they're not there.

Thinking about it, I actually already have all I need: I can just pass an empty `customBlockStyles` to the `DraftEditorBlock` in this custom component, and it won't render any styles.

**Comment by hellendag** [comment]
Yep, that should work.

**Comment by hellendag** [comment]
I made it available in master, so hopefully that helps for now: https://github.com/facebook/draft-js/commit/2b7e3cceae70e74caf6aff588fa1ca10680dffa0
