### ISSUE TITLE
Kebab menu shows empty overlay in single column flex layout mode

### ISSUE THREAD

**Issue by claudiopro** [facebook/draft-js#1873]
**Do you want to request a *feature* or report a *bug*?**

Bug: the kebab menu shows an empty overlay when the Draft.js site is in single column flex layout mode

**What is the current behavior?**

* Shrink the window below 736px to switch to the single column layout
* Click the kebab menu button (three vertical dots) on the right of the menubar
* Observe the window goes blank

Video: https://youtu.be/rXho0KPbMwI

**What is the expected behavior?**

The kebab menu button should not be displayed when the menu empty, or there should be meaningful content in the menu

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Most likely an issue introduced when moving the Draft.js website to Docusaurus

**Comment by juliankrispel** [comment]
thanks for reporting this @claudiopro

**Comment by cojennin** [comment]
This happens on a couple different `docs` pages. Whether the kebab menu is shown or not is controlled by the `onPageNav` value in the Docusaurus siteConfig. It doesn't seem like it can be overridden with configuration on a per page basis.

I made some updates to `docs` pages in #1885 so that a value will always be shown in the kebab menu on every `docs` pages. Seemed easier than trying to code around it.

**Comment by niveditc** [comment]
Fixed in #1885
