### ISSUE TITLE
Pressing Opt-Space scrolls the page down

### ISSUE THREAD

**Issue by spicyj** [facebook/draft-js#19]
If you type Opt-Space to insert a nbsp (on http://facebook.github.io/draft-js/, for example) in Chrome Mac, the page scrolls down a screenful but it probably shouldn't move. Missing preventDefault() somewhere probably.

**Comment by bryanbierce** [comment]
Hey, I'd love to try fixing this. I took a quick look and am thinking it would need to to be caught in the [defaultKeyBindings](https://github.com/facebook/draft-js/blob/master/src/component/utils/getDefaultKeyBinding.js) and that it also might require a check for the option key modifier in the [KeyBindingUtil](https://github.com/facebook/draft-js/blob/master/src/component/utils/KeyBindingUtil.js) am I on the right track?

**Comment by hellendag** [comment]
It could work well to use a key binding for this, yeah. `KeyBindingUtil.hasCommandModifier` could be useful here, though I don't know the expected behavior for <kbd>Ctrl</kbd>+<kbd>Space</kbd> in Windows.

Before using a keybinding, I suggest using a jsfiddle for a minimal repro to determine whether this is a bug in `ContentEditable` or within Draft.

**Comment by spicyj** [comment]
Yeah – this doesn't happen with a plain contenteditable so it's worth first figuring out what Draft does that causes this.
