### ISSUE TITLE
ContentState Typings missing getEntityMap() (Error no Method)

### ISSUE THREAD

**Issue by ipenywis** [facebook/draft-js#1925]
Version: 0.10.5
Issue: Missing **`getEntityMap()`** method declaration on **ContentState** class declaration.

Should be an easy fix, but just wanted to point out to, ty.

**Comment by paigeflourin** [comment]
how to fix this?

**Comment by ipenywis** [comment]
@paigeflourin Just open up **index.d.ts** in `node_modules/@types/draft-js/index.d.ts` and Look for **ContentState** Class declaration.
In the list of Methods add: `getEntityMap(): Immutable.OrderedMap<string, Draft.Model.Entity.DraftEntity>;`
and Save the typings file.

**Comment by claudiopro** [comment]
Hi @ipenywis, I understand this bug is related to [Draft.js TypeScript types](https://www.npmjs.com/package/@types/draft-js)? If so, please [report the issue in the DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/new).

I discourage patching your `node_modules` directory by the way, it is a brittle solution that creates subtle inconsistencies between your development environment and the rest of the world, and defeats the use of a lockfile to pinpoint dependency versions.

**Comment by claudiopro** [comment]
@ipenywis  @paigeflourin PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31706 was merged, you'll find the type definition in the next version of [@types/draft-js](https://npm.im/@types/draft-js) 😄
