### ISSUE TITLE
Add editable elements inside block without the impact of content / selection behavior

### ISSUE THREAD

**Issue by phuczeero** [facebook/draft-js#1973]
I want to add an input (like a comment, notation, ...) inside per HTML block tag, and set its position relative to block. But I don't want the implementation affect current content, selection behavior.
Similar example: https://codepen.io/brijeshb42/pen/amojWq?editors=1010

**Comment by flarnie** [comment]
I came up with something - 
https://codepen.io/paradasia/pen/pqQYRj?editors=0110

<img width="518" alt="screen shot 2019-01-12 at 2 47 04 pm" src="https://user-images.githubusercontent.com/1114467/51079301-8a615800-1679-11e9-8e43-b7eb817c2c89.png">

- Add the 'comment' input into the custom block component, and show/hide it using CSS hover on the parent container to set child `display` property to block/none.
- Pass down a callback from the outer parent all the way to the comment input that will set the editor to `readOnly={true}` when someone focuses the comment input. Otherwise Draft.js hijacks the focus when you try to type in the nested comment input.
- We can make the comment input a controlled component with it's own state.

Hope this helps, if you were going for something else then

**Comment by phuczeero** [comment]
Make sense, I'll try.
Thanks for your help :+1:
