### ISSUE TITLE
ordered list selection

### ISSUE THREAD

**Issue by frankietaylor** [facebook/draft-js#198]
Tried this here (https://facebook.github.io/draft-js/) on Chrome Windows

Steps to reproduce:-
- Type something like this
```
abcd
efgh
ijkl
```
- Select all
- Click on OL
- Try to select everything (either through mouse or keyboard)

Observation:-
1 is not selected, but 2 and 3 are selected. However when copied and pasted in some other editor, even 1 shows up
Pressing delete, will delete everything except 1. (Inconsistent with copy)

Checked the same in Microsoft Word 2013, 2 and 3 are not selected at all. Whatever be the behavior (either select all of 1,2,3 or dont select any of them)

**Comment by hellendag** [comment]
The OL numbers are rendered using CSS, not by natively rendering the numeral. In this way, the numeral is part of the selected content. I'm not sure why the first numeral is not included in the selection.

When pasting elsewhere, since the copied contents are three list items within an `ol`, all numerals should render.

When pressing delete to remove items 2 and 3, as well as the text of item 1, you will be leaving the first item empty but still an `ordered-list-item` block. Therefore the `1` remains.

If we are able to render true lists at some point and allow the browser to render OL numerals, the selection issues should go away. The native behavior would simply not select the numerals at all, which would be the more correct behavior.

In the meantime, I'm not sure there's much we can really do here. I think the paste behavior is correct enough, though the selection behavior is unusual. If there is a block above the first list item, then the `1.` will be selected along with the item.

**Comment by hellendag** [comment]
If we move toward a nested structure for the model, this will probably be resolved. For now, I'm going to close this since I think we're stuck with this behavior as long as `ol` lists are rendered this way.
