### ISSUE TITLE
Question: future releases?

### ISSUE THREAD

**Issue by helenanderson** [facebook/draft-js#2010]
Hi, folks! It seems like this repo is still pretty active, but I notice there hasn't been an official release for over a year. Are there plans for future releases, or are they totally on hold? Any info would be appreciated. Thank you!

**Comment by Daniel15** [comment]
Hey Helen, I'll follow up internally at Facebook to see who's handling releases of Draft.js these days. I think Flarnie was going to work on this, but she's no longer at Facebook.

**Comment by claudiopro** [comment]
Hi @helenanderson, thanks for bringing up this question. We are planning to publish a release in the coming weeks. Currently we Draft.js maintainers at Facebook are volunteering our spare time to respond to critical issues and keep the project alive, and may not be able to move as fast as we would like. Thanks for understanding!

**Comment by helenanderson** [comment]
@Daniel15 @claudiopro Thanks for following up on this! I'll keep an eye out for the new release. Appreciate your time :)

**Comment by claudiopro** [comment]
Following up, I made some time to publish the current master as `0.11.0-beta` with tag `next` on npm: https://www.npmjs.com/package/draft-js/v/0.11.0-beta

Please install with `yarn add draft-js@next` or `npm install --save draft-js@next` and try it out! Let us know of any issues or comments here on the repo 😄

**Comment by carlosagsmendes** [comment]
Thank you @claudiopro. You mentioned that you are using your spare time to respond to critical issues and keep the project alive. Is it no longer being used by FB?

**Comment by Daniel15** [comment]
@carlosagsmendes It's still used a lot at Facebook - the comments box and "Notes" feature on the Facebook site both use it, as well as a lot of internal tools (we have heavily-used internal task management, note taking, and performance review tools that all use it). However I think not a lot of work is being done on it, as it already has most of the features that those use cases require.

**Comment by steida** [comment]
@Daniel15 Thank you for the answer. Btw, does Facebook plan to use DraftJS on mobile devices?

**Comment by Daniel15** [comment]
There was an attempt at using DraftJS on the mobile site, but if I remember correctly there were several issues/bugs with contentEditable on Android, so that was rolled back. I'm not sure whether there's any plans for mobile at the moment.

**Comment by fabiomcosta** [comment]
@steida there is some work being done to make draft-js work on mobile at https://github.com/facebook/draft-js/pull/2035, any help testing that PR is really appreciated.

**Comment by claudiopro** [comment]
Bumping this issue up for visibility, I'm pretty happy by the lack of negative feedback on `v0.11.0-beta` besides known issues with the deprecation of DraftEntity regressing from the previous `v0.11.0-alpha` branch (#2038, #2043), and broken flow types in master addressed with #2027.

As things stand, we are planning to release `v0.11.0` in mid April. Stay tuned for an announcement!

**Comment by thibaudcolas** [comment]
@claudiopro it's a bit hard to meaningfully review the changes between v0.10.5 and the latest v0.11 beta since there's been so many commits ([225](https://github.com/facebook/draft-js/compare/v0.10.5...0.11.0-beta) if I counted this right). Could you share a changelog / release notes for v0.11, so we know what to test exactly?

**Comment by claudiopro** [comment]
Sure @thibaudcolas, we are going to keep the community informed about new features, breaking changes, and fixes as usual. Please track the changes in #2052.

**Comment by ddelrio1986** [comment]
@claudiopro I know you mentioned a planned v0.11.0 release for mid-April. I'm guessing those plans have changed a bit. Is there a new expected time for a v0.11.0 to release?

**Comment by claudiopro** [comment]
We're going through end of half review and planning for the next half. I'm waiting for the other maintainers to complete their H2 planning to understand what's our firepower to keep the project healthy and manage the OSS community.

I could make time to work on it alone if things stand like they were this half and tentatively set a date for early September.

The main blocker for us was a problematic upgrade of internal FB code to use the refactored `convertFromHTMLToContentBlocks` utility. My current attack plan is:

- Deprecate the legacy `convertFromHTMLToContentBlocks` by renaming it to `convertFromHTMLToContentBlocks_DEPRECATED` (landed this week with https://github.com/facebook/draft-js/commit/ceaeebf1f50fee452d92d71c5e2008e3d4fb6d9f). This is an intentional change to prompt consumers of code in master to make a deliberate effort to upgrade and report any issues with the new converter.
- Give the community some time to switch to `convertFromHTMLToContentBlocks2` and iron out any blockers found.
- Rename `convertFromHTMLToContentBlocks2` to `convertFromHTMLToContentBlocks` and ship it with v0.11.0

**Comment by claudiopro** [comment]
Good news y'all, all steps outlined earlier have been successful. I'm about to publish 0.11.0 to the npm registry 🎉

**Comment by claudiopro** [comment]
PR: https://github.com/facebook/draft-js/pull/2125

**Comment by Daniel15** [comment]
@claudiopro  Can we close this issue now that 0.11.0 is out? Thanks for all your hard work 😃

**Comment by sbusch** [comment]
Thanks for publishing on npm!

Just noticed there's no tag set in git and also no entry on the GitHub releases page. Would be great to have that, too :-)

**Comment by claudiopro** [comment]
I guess so? Unless we want to keep it open for... future releases 😁

**Comment by claudiopro** [comment]
@sbusch okay that was easy:
```sh
$ git push origin --tags
```

**Comment by claudiopro** [comment]
Okay nevermind, figured that too 😅  I'll update the releases adding a detailed changelog over the next few days. I'll close this issue now, thank you all for supporting the `v0.11.0` release 🎉
