### ISSUE TITLE
Double symbol issue

### ISSUE THREAD

**Issue by vmakhaev** [facebook/draft-js#202]
I'm trying to make collaborative editing for Draft based on CRDT. For this I need to store content state in database and send it between clients, while selection state can be stored in component's state. For this I deconstruct entity state in `onChange` handler and then construct it again in `render` function.
The problem is that on symbol input, it triggers `onChange` two times and and ends up with two symbols in editor instead of one.
For your convenience, I created an [example](https://github.com/vmakhaev/draft-js/tree/master/examples/issue) that reproduces problem. It is fork from `rich` example and saves everything in state.

**Comment by gscottolson** [comment]
You might consider `handleBeforeInput`.

**Comment by vmakhaev** [comment]
@gscottolson I'm trying to use `handleBeforeInput`. I assume, that you mean that I should reject some symbols by returning `true`, but it is called just once, before `onChange` is called two times. So I can reject all input or nothing.

**Comment by gscottolson** [comment]
I believe that modifying the editor state [within your `onChange` handler](https://github.com/vmakhaev/draft-js/blob/master/examples/issue/rich.html#L85-L88) might be contributing to your problem. Here is an [excerpt](https://github.com/facebook/draft-js/issues/92#issuecomment-189457952) from another issue:
> When you changed to a new `ContentState` within `handleChange`, the `nativelyRenderedContent` value and your new `ContentState` did not match up. When this occurs, the component will re-render, because it believes that the current `ContentState` is not natively rendered. The event still occurs and the character is natively inserted, but your re-render also takes place. The character thus appears twice.

I think you can use `EditorState.push` instead of [creating a new `EditorState`](https://github.com/vmakhaev/draft-js/blob/master/examples/issue/rich.html#L117-L123) from scratch for each component `render`.

**Comment by vmakhaev** [comment]
@gscottolson `EditorState.push` works. Looks like I missed this moment in docs. Thanks.
