### ISSUE TITLE
Incorrect behavior in ordered lists

### ISSUE THREAD

**Issue by alina7091** [facebook/draft-js#2034]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Ordered lists do not preserve count when interrupted by an unordered list

You can repro it in any draft playground
1. Create an ordered list item, type something in
2. Hit enter, go to a new line - see the list is continuing.
3. Now, switch the type of the current item to unordered list and hit tab to make it nested.
4. Go to a new line and create a new ordered list item.

Expectation: list continues from 2. 
Reality: list starts with 1. again

![Screen Shot 2019-03-13 at 2 25 27 PM](https://user-images.githubusercontent.com/18543042/54315870-8af46d00-459c-11e9-8b8c-56028fb509f7.png)

**What is the expected behavior?**
List continues from 2.
![Screen Shot 2019-03-13 at 2 31 44 PM](https://user-images.githubusercontent.com/18543042/54315945-c131ec80-459c-11e9-9d25-325c5952c3ad.png)

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
 0.10.5

**Comment by alina7091** [comment]
Seems somewhat similar to the existing issue https://github.com/facebook/draft-js/issues/1903 ?

**Comment by thibaudcolas** [comment]
Yes, this is the same issue as #1903, and also #1392.

**Comment by claudiopro** [comment]
@alina7091 this bug is fixed in master as you can see for yourself on the live demo on https://draftjs.org

In order to use a version of Draft.js that contains the fix, please add `draft-js@next` to your dependencies instead of `0.10.5`. Please let us know if there are any issues with that version. 

If you're curious, the tag `@next` currently points to the `0.11.0-beta2` version. If no major issues  are reported by users, we'll publish it as `@latest` in a few weeks. We're not publishing a new version directly because there hasn't been a release since `0.10.5` in nearly two years, and we may break dependent projects. This way, we can let you test the new version and fix any issues you may find.
