### ISSUE TITLE
facing the issue on typing text in android chrome 

### ISSUE THREAD

**Issue by shivam-dev** [facebook/draft-js#2090]
i am using latest version of draftjs and facing issue on mobile browser on typing.

i am not able to remove written text using back button.

**Comment by robbertbrak** [comment]
@shivam-dev As noted on https://draftjs.org/docs/advanced-topics-issues-and-pitfalls.html#mobile-not-yet-supported, Draft does not officially support Android yet.

That said, Android support has become much better in a recent commit (https://github.com/facebook/draft-js/commit/634bd297f1646934087051b1149164b01a09a136), which has not been released yet. Could you try if your issue is solved when you use the master branch of Draft?

**Comment by claudiopro** [comment]
Hi @shivam-dev, please try the newly released `v0.11.0` and let us know if this is still an issue. I'll close this for now.
