### ISSUE TITLE
Feature: Mentions 

### ISSUE THREAD

**Issue by thaoms** [facebook/draft-js#2137]
Since the draft-js-plugins repo is not maintained anymore, is there a way or example how to implement mentions/suggestions popup?

I want this exact behaviour: https://www.draft-js-plugins.com/plugin/mention

Is this possible only with decorators?

Thank you!

**Comment by jf97** [comment]
What do you mean "Is this possible only with decorators?"  

Since I wanted all the flexibility that came with using Draft.js out of the box (instead of using the draft-js-plugins-editor), I built my own mentions popup.  

From a high level, the way it works is: 
1) When you hit the "@" key or "#" key, instead of letting Draft handle the input, I intercept it using the `handleBeforeInput` api.  
2) I insert an entity of type "ENTITY_TRIGGER" with "@" or "#" depending on what you typed.  
3) Because the ENTITY_TRIGGER entity is rendered as a React Component there will be a componentDidMount() function where I can "grab" the position of the React Component that just mounted. 
4) I send the position of the trigger back to the parent <App />, which I can modify to correctly position the Mentions menu. 

My basic `<App />` structure is as follows: 

```
changeEntityMenuPosition(top, left) {
     this.setState({ entityMenu: {top: top, left: left} })
}
render() {
    return <div>
        <Editor
            ...
            onChange={this.onChange}
            editorState={this.state.editorState} />
        
        <MentionMenu
            positionTop={this.state.entityMenu.top}
            positionLeft={this.state.entityMenu.left}
            onChange={this.onChange}
            editorState={this.state.editorState} />
    </div>
}

```

Thus, I can use the current EditorState to find the text that I should be searching for in <MentionMenu />, perform edits as needed in the <MentionMenu />, and when I'm finished pass it back up to the <App /> via `onChange()`.  

The big question, then is: How do you pass the position of the ENTITY_TRIGGER entity back to the parent? By creating the <EntityTrigger /> component within a scope where it has access to the <App /> methods.  You can try something like this: 

```
export const generateEntityTrigger = (callback) => {
	class EntityTrigger extends Component {
		componentDidMount() {
			const absolutePosition = positionEntitySuggestions(this.el)
			const max = document.body.clientWidth
				
			callback(absolutePosition.top, absolutePosition.left)
		}
	
		componentDidUpdate() {
			this.componentDidMount();
		}
		
		render() {
			return (<span className="trigger" ref={el => this.el=el}>{this.props.children}</span>)
		}
	}

	return EntityTrigger; //Now our <EntityTrigger /> will call the callback every time it mounts
}

```
What is returned from this function is a <Component /> that you can then use normally.  Just pass into this function the method from the parent.  I chose to do it inside the decorator: 

```
export const generateDecorator(entityTriggerCallback) => {
	return new CompositeDecorator([
		{
			strategy: getEntityStrategyByType("ENTITY_TRIGGER"),
			component: generateEntityTrigger(entityTriggerCallback)
		}
	])
}
```

And feed the `entityTriggerCallback()` to the decorator in the <App /> constructor: 
```
class App extends Component {
        constructor(props)
		//...
		this.decorator = generateDecorator(this.changeEntityMenuPosition)
	}
        ...
}
```

Thus the method `this.changeEntityMenuPosition` gets passed from the <App /> to the Decorator Generator, and finally to the Entity Trigger component, where the function will be called every time the Entity Trigger mounts. 

Of course this has downsides: 1) You need to figure out when to insert the entity trigger, and when to remove it (i.e. when someone's typing '@' b/c of an email address not b/c they want to mention someone.), and 2) your position doesn't get updated unless your EntityTrigger component is mounting for the first time.
