### ISSUE TITLE
Current inline styles are lost when block type is changed

### ISSUE THREAD

**Issue by rnicholus** [facebook/draft-js#228]
I noticed this when integrating Draft.js into my own application. In my case, I was setting per-block alignment based on user input by changing the block type using `RichUtils.toggleBlockType`. When I do this, if there are any existing currently inline styles, they are lost.

I can reproduce the same behavior on the [live Draft.js demo](https://facebook.github.io/draft-js/). Steps to reproduce:

1. Click bold and or italic.
2. Click the UL or H1 or BlockQuote button (or any other button that changes the block type). 

Notice the bold/italic style has been reverted. This does _not_ occur if you type some text in between steps 1 and 2. I attempted to trace the exact issue in the code, but due to my relative unfamiliarity with the codebase, I was unable to locate the specific bug or determine a suitable workaround. If you have any advice regarding a workaround, that would be most helpful.

Thanks much for a spectacular library!

**Comment by hellendag** [comment]
To clarify, are you selecting "Bold" while the cursor is in a collapsed (zero-character) state, then switching to H1?

If so, the reason is that `inlineStyleOverride` is nullified when pushing a new `ContentState`: https://github.com/facebook/draft-js/blob/master/src/model/immutable/EditorState.js#L388

This could probably be avoided here if the `EditorChangeType` is `'change-block-type'`. If you'd like to experiment with it and submit a PR, please do. :)

And you're very welcome! :)

**Comment by rnicholus** [comment]
>To clarify, are you selecting "Bold" while the cursor is in a collapsed (zero-character) state, then switching to H1?

Yes, that is correct. The same issue occurs when I select H2, H3, or any other button that changes the block type. 

> This could probably be avoided here if the EditorChangeType is 'change-block-type'.

Adjustments to the push method of `EditorState` suggest that you are correct. Thanks for your help! I'll follow up with a pull request shortly.

**Comment by rnicholus** [comment]
I just opened up a PR - #229.
