### ISSUE TITLE
change types undocumented, and can be simplified?

### ISSUE THREAD

**Issue by ianstormtaylor** [facebook/draft-js#241]
Hey, right now it looks like the `EditorChangeType` logic is undocumented, except for a mention of it in [the `EditorState.push` doc](https://facebook.github.io/draft-js/docs/api-reference-editor-state.html#push). 

I was also wondering while looking through it, might it be easier to instead create `Change` (or `Modification`) objects that have an associated type, and apply them directly with `.push`, as in:

``` js
const change = Modifier.setBlockType(content, range, 'my-block')
const newState = EditorState.applyChange(editorState, change)
```

Instead of the current API of:

``` js
const newContent = Modifier.setBlockType(content, range, 'my-block')
const newState = EditorState.push(editorState, newContent, 'change-block-type')
```

The downsides to the current one as I see them are:
- The `changeType` doesn't have to be hardcoded in both operations.
- ~~The static `.push` method takes an instance, so why not make it an instance method.~~
- `push` doesn't sound quite right. (I saw that the name was pending change in the doc.)

If the `change` was serialized, this seems useful for https://github.com/facebook/draft-js/issues/93 as well.

Edit: actually thinking about it more, I'm assuming that `.push` is static since it returns a new `EditorState`, and making it an instance might be confusing. Edited to reflect that.

**Comment by ianstormtaylor** [comment]
Using it more, the current API feels very convoluted to work with, having to remember that `Modifier` takes a `ContentState`, while `push` takes an `EditorState`. (If transforms were to be applied to `SelectionState` as well later on, only taking `ContentState` would be a problem.)

Taking the concept further, it wouldn't be far off to be able to expose convenience methods for creating and applying transforms directly on `EditorState` to get things to a saner lever of terseness:

```js
const newState = EditorState.transform.setBlockType(editorState, selection, 'my-block')
```

**Comment by hellendag** [comment]
Thanks for opening this. I always enjoy a good API discussion. :)

The goal of the `Modifier` methods is to provide `ContentState` objects that the caller can then perform further operations on. This is independent of any modifications to the `EditorState` -- the end goal of a `Modifier` method output value is not always to `push`.

If a different type of object (i.e. `Change`) were returned instead, then this would not be possible unless the `Change` object contained the full `ContentState`. The caller could then extract it back out of the `Change` object in order to operate on it, I suppose, but I'm not sure that the benefit of encapsulating the `EditorChangeType` is worth the overhaul.

> The changeType doesn't have to be hardcoded in both operations.

This value should only be used for `EditorState.push` -- where else do you see it?

I freely admit the documentation on `EditorChangeType` should be improved. :) There is a documentation issue open on it, and I need to get to it.

> push doesn't sound quite right. (I saw that the name was pending change in the doc.)

Yeah, I had been thinking `EditorState.pushContent` or something similar, since `push` doesn't really mean anything on its own.

> const transform = Transform.setBlockType(editorState, selection, 'my-block')
> const newState = EditorState.applyTransform(editorState, transform)

Again, the goal of a `Modifier` method is not to provide any sort of changes to `EditorState`, but to provide a new `ContentState` based on a different `ContentState`, a `SelectionState`, and some parameters.

Could this be clarified by renaming some of the modules, perhaps? The name "Modifier" does not necessarily imply the above, so perhaps that is a point of confusion.

**Comment by ianstormtaylor** [comment]
> The goal of the Modifier methods is to provide ContentState objects that the caller can then perform further operations on. This is independent of any modifications to the EditorState -- the end goal of a Modifier method output value is not always to push.

Ah interesting, that makes sense. I think framing it in terms of transactions that can be applied to the editor is still useful (and required for implementing any sort of collaboration). In the `Modifier` case, it's already fairly close. Instead, "transforms" could be applied to either `EditorState`, `ContentState` or `SelectionState`. Something like:

```js
const transform = new ContentTransform(range, options)
const newContentState = contentState.applyTransform(transform)
```

This would be the equivalent of the concept of `Modifier` as it currently stands (correct me if I'm wrong, might still be misunderstanding!). The same could be done with the selection:

```js
const transform = new SelectionTransform(...)
const newSelectionState = selectionState.applyTransform(transform)
```

And at the top-level, the `EditorState` could know how to apply each type of transform, such that it figures them out and applies them to the proper child data object.

```js
const contentTransform = new ContentTransform(...)
const selectionTransform = new SelectionTransform(...)
state = state.applyTransform(contentTransform)
state = state.applyTransform(selectionTransform)
```

So you could be lower level and mutate `contentState` multiple times in isolation, or stay higher level and just pass in top-level transforms into the `editorState` like you would when receiving collaborative changes from the server?

**Comment by lacker** [comment]
It seems like this discussion has converged, so I'm going to close the issue. Thanks for bringing this issue up!
