### ISSUE TITLE
Failed to execute 'extend' on 'Selection': This Selection object doesn't have any Ranges

### ISSUE THREAD

**Issue by kartikpandey2** [facebook/draft-js#2423]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
I am implementing checklist using draftjs. When I toggle checkbox it throws `Uncaught DOMException: Failed to execute 'extend' on 'Selection': This Selection object doesn't have any Ranges.` error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem: https://jsfiddle.net/Lrdnv34c/3/.**
* Open js fiddle link
* Create new checklist and write some content in editor block and then try to toggle checkbox.

**What is the expected behavior?**
Toggle should work without error.
Infact toggle works fine if there is no content in editor block.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Draft.js version: 0.11.5
Browser: Google chrome 81
OS: macOS catalina 10.15

**Comment by mrkev** [comment]
This has been fixed on master, but there hasn't been a release to npm yet. It will be there on the next update. See https://github.com/facebook/draft-js/commit/d53fa7ab92864d47805c9e7509d7bde951372f58.

https://github.com/facebook/draft-js/blob/0585b68fed5e1d732692f24989fa0fb1dd54c6f2/src/component/selection/setDraftEditorSelection.js#L271-L273

I can't provide a specific timeline, but it'll be sooner rather than later since it includes other important fixes. There's a couple of things that need to be figured out before the release is published.
