### ISSUE TITLE
trouble for using custom block 

### ISSUE THREAD

**Issue by nickhsine** [facebook/draft-js#250]
This issue is related to this one, https://github.com/facebook/draft-js/issues/211
I am modifying the `tex` example; I change the block type from `media` to `tex`.
However, deleting the `TeXBlock` by typing backspace occurs the `Uncaught Error: Got unexpected null or undefined` and `Uncaught Invariant Violation: Unknown DraftEntity key.` error.
Should the custom block type be one of the `DraftBlockType` such as `media`?

**Comment by tasti** [comment]
The reason why you're seeing the error is due to special backspace handling for `media` block types as you can see https://github.com/facebook/draft-js/blob/master/src/model/modifier/RichTextEditorUtil.js#L123.

One way to solve this would be to write your own `handleKeyCommand`, which isn't great.

A more reusable approach would be to have block types that can inherit traits from one of the default block types. An example of a convention to handle this would be that you name your block type `media-tex`. Then in the draft-js core, instead of `block.getType() === 'media'`, we do `block.getType().startsWith('media')`.

Just a though, happy to discuss this further :)

**Comment by nickhsine** [comment]
@tasti 
Thanks for your quick response :)

However, how can I let the draft-js core to do ```block.getType().startsWith('media')```? 
Or will this thought be implemented in the future?

**Comment by tasti** [comment]
This would need a bit more discussion in case there are better alternatives (my suggestion was what first came to mind).

If you want, you can create a PR by changing all instances in the core to `block.getType().startsWith('media')` and we can investigate from there.

**Comment by nickhsine** [comment]
You mentioned that writing ```handleKeyCommand``` isn't a good way.
Could you explain more why it isn't good?
I think use media as prefix, such as ```media-tex```, is kind of implicit.

**Comment by tasti** [comment]
> You mentioned that writing handleKeyCommand isn't a good way.
Could you explain more why it isn't good?

I meant it in the sense that you'd lose and have to reimplement everything in `RichTextEditorUtil. handleKeyCommand()` if you wanted all of it.

Now that I think about it, you don't really need to. You can create a chain of `handleKeyCommand`s, and if your check fails (returns `null`), then use `RichTextEditorUtil. handleKeyCommand()`.

> I think use media as prefix, such as media-tex, is kind of implicit.

It is, and since this is a pretty edgy-case, we probably don't have to do this. The above suggestion should be sufficient for what you're trying to accomplish.

**Comment by nickhsine** [comment]
> > You mentioned that writing handleKeyCommand isn't a good way.
> > Could you explain more why it isn't good?
> 
> I meant it in the sense that you'd lose and have to reimplement everything in RichTextEditorUtil. handleKeyCommand() if you wanted all of it.
> 
> Now that I think about it, you don't really need to. You can create a chain of handleKeyCommands, and if your check fails (returns null), then use RichTextEditorUtil. handleKeyCommand().

Yes, this is what I want to implement. Use my own ```handleKeyCommand``` handler first, if fails, then use ```RichTextEditorUtil. handleKeyCommand```.

> > I think use media as prefix, such as media-tex, is kind of implicit.
> 
> It is, and since this is a pretty edgy-case, we probably don't have to do this. The above suggestion should be sufficient for what you're trying to accomplish.
> 

thanks for your suggestion :)
