### ISSUE TITLE
cmd+backspace should delete the \n if there is no text in the selected line

### ISSUE THREAD

**Issue by rickyvetter** [facebook/draft-js#295]
The default behavior of most multi-line inputs allows you to spam cmd+backspace to delete multiple lines of text. I'm always surprised when I can't in draft.

**Comment by hellendag** [comment]
To my knowledge, Draft's behavior is correct -- <kbd>Cmd</kbd>+<kbd>Backspace</kbd> should delete the current visual line of text.

(This textarea exhibits the same behavior.)

Which browser/OS do you use? I'm not aware of discrepancies with this key command.

**Comment by hellendag** [comment]
Oh hey @rickyvetter didn't see that it was you. :P

**Comment by rickyvetter** [comment]
Hey @hellendag :) the behavior is correct when there is text in line you are deleting. The discrepancy I see is when there is no more text in the line. The textarea I'm typing in (and regular text areas in Chrome/OSX) make it so pressing cmd+backspace while your current line is empty deletes the \n, moving your cursor from the 0 position in the bottom line to the final position in the line above it.

**Comment by hellendag** [comment]
Ahh, interesting. I think the fix for this should be pretty straightforward, within [keyCommandBackspaceToStartOfLine](https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/commands/keyCommandBackspaceToStartOfLine.js#L39).

If the target range is empty:

- If the selection offset is zero, remove the current block.
- Otherwise, select one character backward and remove that.
