### ISSUE TITLE
example 'entity' and 'tex' not working

### ISSUE THREAD

**Issue by Beingbook** [facebook/draft-js#308]
Two examples have same error.

<img width="409" alt="2016-04-14 9 53 01" src="https://cloud.githubusercontent.com/assets/2682865/14528616/5341edb2-028b-11e6-835c-0460210097e7.png">
<img width="654" alt="2016-04-14 9 53 13" src="https://cloud.githubusercontent.com/assets/2682865/14528617/534843e2-028b-11e6-9bb5-44b71fc02c94.png">

**Comment by thisbejim** [comment]
Can confirm I am getting this too.

**Comment by stephenkiers** [comment]
It seems to be getting a OrderedMap passed into it, instead of a block. 

![screen shot 2016-04-15 at 10 56 27 am](https://cloud.githubusercontent.com/assets/1245512/14568871/bd6f00fe-02f8-11e6-9ce8-e556451ba9d4.jpg)

I tried figuring out, but I was using this example to learn draft.js so it is a little over my head at the moment

**Comment by stephenkiers** [comment]
It seems to be padding through a contentstate object instead of an array here; not sure why
![screen shot 2016-04-15 at 11 42 13 am](https://cloud.githubusercontent.com/assets/1245512/14569983/32b69c2c-02ff-11e6-9920-16dd044b3704.jpg)

**Comment by hellendag** [comment]
Interesting. I think I know what I broke here. I'll take a look.
