### ISSUE TITLE
AtomicBlockUtils is not parsing images after loading editor content from database

### ISSUE THREAD

**Issue by swaathi** [facebook/draft-js#309]
I'm using AtomicBlockUtils to manage file uploads in my document creation tool. It's properly displaying the image when I upload it the first time and also saves to the DB without a problem. But when I try to edit the created document, it doesn't seem to parse the image again, in fact it doesn't even display it in the editor content when i inspect element on it.

Here's the content that's saved to the DB,

    <figure class="" data-block="true" data-editor="dv6p5" data-offset-key="c2o7s-0-0" contenteditable="false" data-reactid=".b.5.0.$editor0.0.0.$c2o7s">
        <img src="http://www.popsci.com/sites/popsci.com/files/styles/large_1x_/public/new-google-logo.jpg" style="width:100%;" data-reactid=".b.5.0.$editor0.0.0.$c2o7s.$c2o7s">
    </figure>

Here's the code itself,

    // File upload strategy
    function mediaBlockRenderer(block) {
      if (block.getType() === 'atomic') {
        return {
          component: Media,
          editable: false,
        };
      }

      return null;
    }

    var Media = function Media(props) {
      var entity = Entity.get(props.block.getEntityAt(0));
      var src = entity.getData().src;

      return <Image src={src} />;
    };

    var Image = function Image(props) {
      return <img src={props.src} style={{width: '100%'}} />;
    };

Is there anything wrong with it parsing it from the DB?

**Comment by Beingbook** [comment]
I think you should convert your text data as `RawDraftContentState`.
[This link] might help you.

**Comment by swaathi** [comment]
I've tried this to. But when I `convertFromRaw` with the DB content, it throws a parsing error.

**Comment by max-mykhailenko** [comment]
You should use `convertFromHTML`, but now it's doesn't work with `img` tag too.

**Comment by swaathi** [comment]
Oh! Yeah I do use `convertFromHTML`, and it just doesn't parse the `img` tag. Is there any workaround for this?

**Comment by max-mykhailenko** [comment]
Don't know, I need this feature too.

**Comment by hellendag** [comment]
`convertFromHTML` will probably not support `img` tags within HTML paste at any point, or at least at any point soon.

As @Beingbook suggests, you should create a `RawDraftContentState`. This is the format that `Draft` is able to ingest, and the framework defers to the developer to determine how best to convert from the optimal storage format (which may vary widely across use cases and developers) into this ingestion format.

Note that this is the case because Facebook has a limited set of needs for HTML. We do not store our content as HTML, and it would not be appropriate for us to release tools that we do not use in production. Some people want to store their content as some flavor of markdown, others as some flavor of markup, others as something else entirely. :)

Note also that my recommendation is not that you store the direct HTML output of the Draft editor, which it looks like you may be doing. For the Draft framework, HTML/DOM is treated as an implementation detail for rendering to browsers, and no guarantees are made that the HTML it generates in the browser can be reliably used for storage. Instead, `convertToRaw` provides a utility that will output a `RawDraftContentState` that you can then serialize to any format you like.

Based on the description in this issue, this probably means you need a custom conversion utility to go from your stored HTML to the `RawDraftContentState`, and perhaps a utility to do the opposite as well.

**Comment by swaathi** [comment]
Thanks for the detailed explanation. Unfortunately when I tried this, I ran into a parsing error when I try to edit the content (i.e, load the `RawDraftContentState` from the DB, and covert it).

    Uncaught TypeError: Cannot convert undefined or null to object

This is how I convert to raw format,

    var content = this.state.editorState.getCurrentContent();
    var text = convertToRaw(content)

And this is how I retrieve the HTML,

    var processedHTML = convertFromRaw(this.props.text);
    var eState = EditorState.createWithContent(
      ContentState.createFromBlockArray(processedHTML),
      DECORATOR
     );

Is there some special format I should save the content in? Or should I do some preprocessing before `convertFromRaw`?

This is the DB content,

    {"blocks"=>{"0"=>{"key"=>"10dg0", "text"=>"This is going to save in DraftJS raw format.", "type"=>"unstyled", "depth"=>"0"}, "1"=>{"key"=>"9q8f9", "text"=>"", "type"=>"unstyled", "depth"=>"0"}, "2"=>{"key"=>"6vb58", "text"=>"RawwwwwwR.", "type"=>"code-block", "depth"=>"0"}}}

**Comment by swaathi** [comment]
Oops! Looks like that was an issue on my side. Thanks for the help! It works when I `convertFromRaw` now. :)

**Comment by kevinguard** [comment]
@swaathi What was the error you made that you mentioned you managed to resolve? I am having the same issue but it manifest itself only when there is only text in my contents. When I add an image or video, it simply works since it will have an `entityMap` for it. For text, however, there is no `entityMap` and therefore it fail. Thoughts?

**Comment by ducnvhn** [comment]
hi @kevinguard . I have same problem you did. Did you manage to resolve? My content state cannot covert from raw until it has a entity (like img / video). Only unstyled block will not be able to convert.

**Comment by innovagen** [comment]
> @swaathi What was the error you made that you mentioned you managed to resolve? I am having the same issue but it manifest itself only when there is only text in my contents. When I add an image or video, it simply works since it will have an `entityMap` for it. For text, however, there is no `entityMap` and therefore it fail. Thoughts?

I have same issue when there is no entityMap
