### ISSUE TITLE
Draft breaks under weird circumstances

### ISSUE THREAD

**Issue by gabriel-miranda** [facebook/draft-js#326]
Hi! My team and I were using draft to build a beautiful rich text editor, so first of all, thank you for open sourcing this, is great!

The issue that we found was this:

1. Focus on draft
2. Add an `atomic` block
3. Press `up arrow` an position in the first editable block (non-atomic)
4. Press `del` (on windows) or `fn + del` (on mac I think)
5. Try to write something
6. Error `Uncaught Invariant Violation: Unknown DraftEntity key.`

And draft is left broken

I think the solution will be focus in the next editable block and if there's none, add a new one.
I would like to hear what you guys think about this.

Thanks in advance, best regards, Gabriel.

**Comment by guitardave24** [comment]
Are you rendering children in your entity decorator?

**Comment by gabriel-miranda** [comment]
@guitardave24 it doesn't matter, try it in the `media` example of this repo, it happens too

**Comment by gabriel-miranda** [comment]
Any updates on this guys?

**Comment by hellendag** [comment]
Yeah, this breaks if the text block with the cursor is empty, but seems to work properly otherwise. The cursor is left in an uncertain state, hence the error.

(I think the media examples may also have some selection state issues due to using `window.prompt`, I'm not sure. cc @tasti)

[`RichUtils.onBackspace`](https://github.com/facebook/draft-js/blob/master/src/model/modifier/RichTextEditorUtil.js#L106) and [`RichUtils.onDelete`](https://github.com/facebook/draft-js/blob/master/src/model/modifier/RichTextEditorUtil.js#L168) should handle this for you, though their behavior seems to need some tweaking for the empty block case.

I think the `SelectionState` is not being moved upward properly when the empty block is removed.

**Comment by guitardave24** [comment]
Correct. I fixed this by locally overriding backspace key command and
checking explicitly for the previous block as atomic, removing it, and
setting the style and cursor in the right place It's not much code and I
expect to delete it once draft is fixed.

Would paste code if I weren't on my phone

**Comment by hellendag** [comment]
Cool. Putting together a fix now.
