### ISSUE TITLE
Use IMMUTABLE entity for pasted link url.

### ISSUE THREAD

**Issue by southerncross** [facebook/draft-js#329]
Hi, I have a little suggestion about processing pasted link.

While Draft is processing pasted HTML fragment, it set the url text to `LINK` entity.
The `LINK` entity is `MUTABLE`(default), so users can modify it. However, they are actually modifying the link's display name, not the url.

I know that LINK entities are generally mutable just as the doc says:
> For instance, link text is generally intended to be "mutable" since the href and linkified text are not tightly coupled.

But for the pasted links, I think it is better to make them "immutable" because this kind of link comes from **implicit** conversion, compared with those links which are entered by clicking "Add link" button.

So, if a user plans to modify the pasted link url, commonly they will just do it directly(modifying the display name) instead of remembering to set the link through "Add link" button. And it tends to cause trouble.

The following example shows that user can still reach the blog site(of course they can...) even if they have delete part of the url. Strange behavior, isn't it?

![tmp](https://cloud.githubusercontent.com/assets/3861465/14683608/36916d64-075e-11e6-9693-8f9183624832.gif)

So I suggest that Draft treat the pasted link entity as IMMUTABLE. In that case, if a user is trying to modify the link, the entire link url will be removed. Prevent the strange behavior.

Just like that:

![tmp](https://cloud.githubusercontent.com/assets/3861465/14683994/3e8fdc88-0760-11e6-820d-fabf49d987bf.gif)

**Comment by hellendag** [comment]
There is an important distinction to be made between implicit links and explicit links, as you note.

Specifically, implicit links need no entity representation at all -- the text itself is sufficient to serve as the "metadata" of the link. For these, my recommendation would be to use only a decorator, and no entity whatsoever. This is what we do in FB Notes, for example.

In the paste processor, however, we can't currently know whether the developer wants to make the pasted link implicit or explicit. All we know is that there is an anchor tag. We could match the text contents of the anchor tag with the `href` value and take a guess about whether it should be an implicit link, but even then, there could still be problems. For instance, within the paste processor we can't know whether the developer actually wants to decorate implicit links.

The best we can do, then, is to assume that all pasted links are intended to be represented with entities. Since we can't really assume that the links should be `IMMUTABLE`, our safest assumption is that they should be `MUTABLE`.

One option here would be to use `handlePastedText` to manage the paste yourself. If you know that any implicit links should be treated as such, you could avoid creating entities for them, and allow your decorator to do the linkifying work.

**Comment by gabriel-miranda** [comment]
+1 to  `handlePastedText` in my team's implementation we do that.

**Comment by southerncross** [comment]
@hellendag @gabriel-miranda  Thanks for the explanation, didn't notice `handlePastedText` before, sorry.
Yes, you're right, the best way is to handle the pasted text manually.

Well, I didn't read much code of Draft. It seems to be lots of work to customize the  `handlePastedText` :cry: 

Can I just customize the "how to parse link" part? I don't want to copy most of the code of `convertFromHtmlToContentBlock`...

**Comment by gabriel-miranda** [comment]
I don't understand. You can check the pasted text with a regex and do stuff only if you pasted a link, and leave the rest out of it. You can ask for help in the slack https://draftjs.slack.com I don't think this is an issue for github.

**Comment by southerncross** [comment]
Yes, I did it just like you said, use a customized decorator that only decorate link whose url equals its plain text.
Sorry, I'll close this issue.

**Comment by hellendag** [comment]
No problem, glad that worked out for you!

**Comment by southerncross** [comment]
😄
