### ISSUE TITLE
insertAtomicBlock is not storing 'atomic' entity in entityMap of Editor State

### ISSUE THREAD

**Issue by sisodiaa** [facebook/draft-js#352]
I am trying to add image(s) in my draft editor, but insertAtomicBlock is not functioning as expected.
Though it is updating the Blocks of EditorState, it is not updating entityMap as shown in screenshot below.
![image](https://cloud.githubusercontent.com/assets/6825806/14936191/8e077ef8-0f06-11e6-98e8-3770b6a221ca.png)
Here first column is current EditorState, second column is EditorState obtained by calling `AtomicBlockUtils. insertAtomicBlock`, and third one is Entity representing the image.

This is resulting in 

> Uncaught Invariant Violation: Unknown DraftEntity key.

**Comment by hellendag** [comment]
It would help to have more information about what is leading to this error, especially a trace.

Based on the screenshot, I don't see any problems with your data. Since `entityMap` is not expanded in the second column, I can't tell whether the entity has been added. Since you have a `DraftEntityInstance` available, I assume that it actually was set in the global `Entity` map correctly.

What are you using to render your `atomic` block?

**Comment by sisodiaa** [comment]
```
Invariant Violation: Unknown DraftEntity key.
    at invariant
    at Object.get
    at Media
    at ReactCompositeComponentMixin._constructComponentWithoutOwner
    at ReactCompositeComponentMixin._constructComponent
    at ReactCompositeComponentMixin.mountComponent
    at wrapper [as mountComponent]
    at Object.ReactReconciler.mountComponent
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren
    at ReactDOMComponent.Mixin._createInitialChildren
```

I have created [a sample editor](https://gist.github.com/sisodiaa/d2c5e31e52d486887d5e42a73e7cc50d) for adding an image, loosely based on 'Media' example, and there too I am encountering the same error raised by following line
`const entity = Entity.get(props.block.getEntityAt(0));`

In this sample editor I am using a `blockRendererFn` which refers to a React component to render this atomic block.

**Comment by hellendag** [comment]
Can you provide an input other than `window.prompt` and see if that helps?

I've found that `window.prompt` can cause problems with DOM selection state, so you may be ending up with the entity in the wrong place.

**Comment by sisodiaa** [comment]
I have removed `window.prompt` and replaced it with URL string (i.e. no input now), but the error persists.

**Comment by hellendag** [comment]
You need to use a character here: https://gist.github.com/sisodiaa/d2c5e31e52d486887d5e42a73e7cc50d#file-app-es6-L42. Using the empty string, you won't have a character to attach the entity onto. (This is an awkwardness that I'm hoping to improve in the future.)

**Comment by sisodiaa** [comment]
Thanks, it solved the problem.
On a closer look even example code supplied a space character which I misread as an empty string. :(

**Comment by hellendag** [comment]
Sorry for the weird API. :)

**Comment by willbuckingham** [comment]
Figured I'd tack on here because I had a similar error, and this was the only article that even came close to helping me, so maybe I'll help someone else.  I had html that lead off with an <img> tag, and the getting it into the error produced this same/similar error message.  In the end I realized I should at the very least have an empty p tag before the img... <p></p><img....

**Comment by fireb1001** [comment]
i hate myself for this whitespace none-sense
