### ISSUE TITLE
Internet Explorer Korean Input

### ISSUE THREAD

**Issue by phs1919** [facebook/draft-js#359]
As noted in the [documentation](https://facebook.github.io/draft-js/docs/advanced-topics-issues-and-pitfalls.html#ime-and-internet-explorer), Draft js editor has some issues with Korean input on IE 11. While searching for a specific issue/viable workaround, I could only find this [issue](https://github.com/facebook/draft-js/issues/311), which I think is a different problem regarding Korean input. As my use case covers Korean input a lot, it would be great if there is a workaround or possible point from which I can work to solve the issue. Thanks for open-sourcing the project!

**Comment by spicyj** [comment]
As far as I know, IE doesn't fire the proper events when doing IME in Korean so we basically have no idea what's going on. If you find otherwise, we'd be happy to take a pull request _ but based on what I've heard this sounds unlikely to ever work, unfortunately. At Facebook we just don't serve the Draft-based editor to IE users in Korean.

**Comment by robbertbrak** [comment]
@phs1919, in case you are still interested in a workaround for Korean input on IE11, perhaps the commits mentioned above may be of some use to you? It's not pretty (it tries to detect Korean based on the Unicode characters being entered and then reads the input from the DOM instead of the composition event data), but it seems to work reasonably well with the Microsoft IME on both Win7 and Win10.
