### ISSUE TITLE
Didn't find documentation of `blockRenderMap`

### ISSUE THREAD

**Issue by southerncross** [facebook/draft-js#367]
Hi, all

Draft 0.7.0 added a breaking feature `blockRenderMap`, but I didn't find documentation about it. 
Did I miss something?

**Comment by spicyj** [comment]
Looks like we don't have docs yet. You can see some a usage example in the commit: e2037984.

**Comment by mitermayer** [comment]
I am creating a new PR with the docs for it today.

**Comment by southerncross** [comment]
@spicyj @mitermayer Great! 👍

**Comment by nbrady-techempower** [comment]
So I've been banging my head against a wall for a couple of days trying to make a custom block. `blockRenderMap`? This issue is closed but I don't see any docs on it.

After looking over @mitermayer commits from May 5th+ I see that there's #387. It might be a good idea to keep this open until that gets merged. It's been extremely difficult getting anything to work that isn't the standard RichUtils block or inline styles.
