### ISSUE TITLE
Clearing Editor content with cursor in editor causes weird selection behavior when typing

### ISSUE THREAD

**Issue by gdehmlow** [facebook/draft-js#400]
I saved the [DraftJS demo](https://facebook.github.io/draft-js/) page and made this modification to `RichEditorExample`:

```js
  handleBeforeInput(chars) {
    if (chars === 'z') {
      const editorState = EditorState.createEmpty();
      this.onChange(editorState);
      return true;
    }
    return false;
  }

  render() {
    // ...
    return (
        <Editor
            handleBeforeInput={this.handleBeforeInput}
        />
    );
  }
```

The idea is that when I press `z`, the editor content should be completely cleared and I should be able to keep typing normally. Here's what happens instead in Chrome:

![draftbug](https://cloud.githubusercontent.com/assets/850025/15408651/1e9e65da-1dc6-11e6-8b02-1e124fa9e6a6.gif)

What I did here was type `abc`, then I hit `z` to clear the editor. Notice that something weird is happening already - the cursor flies off to the right. Then I typed `abc` again, selected all the text, deleted it, then typed `abc` again. In this last instance, after the `a` was typed, the cursor flipped back to being at position 0. If I log the `onChange` function, it gets correctly set to `1` with text `a`, but then an `editOnSelect` is fired afterwards, inside which `getDraftEditorSelection()` is different from `editorState`.

Safari has problems as well, but they manifest differently.

My workaround is to explicitly `forceSelection` to `0` after creating a new editor state.

**Comment by mitermayer** [comment]
Have you tried doing return false instead of true in there ?

**Comment by gdehmlow** [comment]
That won't serve the example because then the default behavior will take over. This is a simpler / contrived demonstration of the problem I'm actually having.

**Comment by mitermayer** [comment]
@gdehmlow you neeed to create a new empty state with an empty selction modifier applied to it

**Comment by gdehmlow** [comment]
What is the "empty selection modifier"?

**Comment by steviesama** [comment]
You don't want to make a new EditorState using createEmpty(). I've looking at some issues that talk about this. If you ever have any other metadata attached that references plugins or anything, you'll lose all of that. You should push an empty ContentState like the following.

![push](http://i.imgur.com/fO5A1in.png)

Also, that weight behavior will still happen, even if you do it that way. I had opened #410 which addressed this. Also made a 39 second video showing the exact behavior and describing it.

The video:
https://youtu.be/f9BeAssCLR0

**Comment by steviesama** [comment]
I don't think the editor should behave this way, but I figure out a way for it to work, you want to import Modifier, also SelectionState, and ContentState on top of the standard stuff. Refer to the snippet below.

![Modifier](http://i.imgur.com/frB9EnP.png)

Then, you'll need to set up a selectionState that spans from the beginning of the first block in the editor to the end of the last block; as well as setting hasFocus to true as we are using merge and it will screw up the focus otherwise. I included a console.log that turns the object into JSON for debugging.  You want to use Modifier.removeRange() which will return a new ContentState with the removed text (empty). Then do an EditorState.push() and update the state. Here is a snippet below. If you do this, the caret won't go to the right, and the typing behavior will be consistent.

![fixed](http://i.imgur.com/BkukjvJ.png)

That was long winded as hell, and totally unintuitive. Hacking around in this stuff to figure that out is annoying. pushing a ContentState created from ContentState.createFromText('') like another issue resolution said would be a lot more succinct, but that isn't working.

**Comment by steviesama** [comment]
Oops, meant to post that in my issue. Oh well, it's relevant and will fix your issue. Or should.

**Comment by spicyj** [comment]
What about doing…

```js
const editorState = EditorState.push(
  this.state.editorState,
  EditorState.moveFocusToEnd(ContentState.createFromText(''))
);
```

Does that work? I haven't tried it but I believe it should. Related to #73.

**Comment by gdehmlow** [comment]
Yeah that pretty much fixes my issue. Definitely a dupe of #73 so I'll close this.

**Comment by steviesama** [comment]
I posted a response to this on #410.
