### ISSUE TITLE
Advice on setting ContentState blockMap

### ISSUE THREAD

**Issue by paulyoung** [facebook/draft-js#427]
I'm expanding on [this example](https://github.com/facebook/draft-js/blob/8689bcd0a9b3aff402db0720789f3d4028645ef1/docs/QuickStart-API-Basics.md#controlling-rich-text) a little bit and running into an issue.

This works just fine (effectively a no-op):

```javascript
onChange(editorState) {
  const contentState = editorState.getCurrentContent();
  const blockMap = contentState.getBlockMap();
  const newContentState = contentState.set('blockMap', blockMap);
  const newEditorState = EditorState.push(editorState, newContentState, 'change-inline-style');
  this.setState({
    editorState: newEditorState,
  });
}
```

but this produces some strange behavior (still effectively a no-op):

```javascript
onChange(editorState) {
  const contentState = editorState.getCurrentContent();
  const blockMap = contentState.getBlockMap();
  const newBlockMap = blockMap.map((contentBlock) => {
    return contentBlock;
  });
  const newContentState = contentState.set('blockMap', newBlockMap);
  const newEditorState = EditorState.push(editorState, newContentState, 'change-inline-style');
  this.setState({
    editorState: newEditorState,
  });
}
```

More specifically – using the latter, I can type `h` but by the time I've typed `he` it appears as `ehe` and the cursor is after the first letter. This continues creating palindromes like so:

| Typed | Displayed |
| --- | --- |
| h | h |
| he | ehe |
| hel | lehel |
| hell | llehell |
| hello | ollehello |

**Comment by paulyoung** [comment]
FWIW, I've also tried various approaches using the static methods on `Modifier`, all with the same results.

**Comment by hellendag** [comment]
This is a true no-op:

```js
const blockMap = contentState.getBlockMap();
const newContentState = contentState.set('blockMap', blockMap);
```

After this point, `contentState` and `newContentState` are the same object, since `blockMap` is unchanged. The `set` operation is a no-op. This, however...

```js
const newBlockMap = blockMap.map((contentBlock) => {
  return contentBlock;
});
const newContentState = contentState.set('blockMap', newBlockMap);
```

...is not a no-op, since `newBlockMap` is not the same object as the original `blockMap`. Thus, `contentState` and `newContentState` are also distinct objects.

I believe that the problem here, then, is that a new `ContentState` is being applied to your `editorState` during the `onBeforeInput` event loop, which will allow the DOM event to occur when characters are being typed. The native character insertion will not trigger a significant content change (https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnBeforeInput.js#L152), so it will be inserted natively. The editor, however, will re-render because the `ContentState` has changed within `onChange`. The result is that the character is inserted programmatically but *also* inserted natively. I actually would have expected the character to render twice in succession rather than as a palindrome, but I'm guessing there's probably something wonky going on with the DOM selection state during render.

In the case where there is no new `ContentState` to render, the editor will not force a re-render via `shouldComponentUpdate`, and the native insertion occurs normally. (https://github.com/facebook/draft-js/blob/master/src/component/contents/DraftEditorContents.react.js#L74)

The inability to intercept and change `EditorState` for a native `onBeforeInput` event is a known problem, and one that I'd really like to resolve. It's a notable limit on customizable insertion behavior.

Hopefully this helps to clarify!

**Comment by paulyoung** [comment]
@hellendag thanks for the detailed reply. This does clarify things a bit although I'm not sure how to proceed.

Here's is what I was actually trying to do:

```javascript
const newBlockMap = blockMap.map((contentBlock) => {
  ...

  const characterList = contentBlock.get('characterList');

  // Create a new character list with updated `CharacterMetadata`
  const newCharacterList = ...

  return contentBlock.set('characterList', List(newCharacterList));
});
```

If any alternatives come to mind, please share!

**Comment by paulyoung** [comment]
I read the docs and thought about this some more, and have some ideas.

Thanks again for the help!

**Comment by rylev** [comment]
This seems to be related to the issue I opened here: https://github.com/facebook/draft-js/issues/496 Any ideas on how to work around this?
