### ISSUE TITLE
Needing information on which line the caret is positioned

### ISSUE THREAD

**Issue by delijah** [facebook/draft-js#429]
This is a feature request. It would be extremely helpful, if there would be any information on which line the current caret is positioned. For the whole editor, but also per block and/or per selection.

**Comment by hellendag** [comment]
Do you mean the visible rendered line of text?

**Comment by delijah** [comment]
Yes exactly. An example:

I see the editor, i type some letters, words, paragraphs. Let's assume there are 3 paragraphs now. The first has 1 visible rendered line of text, the second paragraph/block has 3 visible rendered line of text. The user klicks in the second line of the second paragraph/block.

Now i'd like to get somehow the information that:
- The caret is positioned on the 3rd line of the editor
- The caret is positioned on the 2nd line of the (second) block
- The caret is positioned on the 1st line of the selection

In my case this is useful because i am implementing block widgets. So if the user moves trough the text with the arrow keys, let's assume he is moving the caret down, line by line, i need to find out if the next line is a widget or still text. So basicly i need to know if the caret is on the first or the last line of text of a block. This also means, that i need to know the total lines of text per block.

Might be useful for other purposes as well?..

**Comment by guitardave24** [comment]
What delimits a line in your use case, a period (as in a sentence) or a newline (as in a soft newline)? You could pretty easily implement this on your own by getting the current selection position and figuring out what block you're in and which line based on the selection offsets...

**Comment by delijah** [comment]
I am talking about the visual appearance. This means it doesn't matter what delimits a line.

Hmm.. but then i would have to calculate the height of one line (by font-size and line-height etc.), right?

Not sure if i completely understand your proposal.

**Comment by thesunny** [comment]
Hi delijah, this is related to https://github.com/facebook/draft-js/issues/203 and as you noted it is an important piece in making atomic block navigation possible.

I've given it some thought and the only obvious way I can think of to make it work will only detect with accuracy whether the user is on the first line or the last line (or both). For your purposes, it seems this is all that is necessary.

We do this by finding the dimensions and position of the current block. Then we find the current dimensions and positions of the current selection. From there, we can figure out if the dimensions and position of the selection appear to be on the first or last line or both. We may be able to guess the exact line as well but given that line heights can vary depending on the styling, I'd give this a smaller chance of being accurate for all cases.

First, you can find the dimensions and position of the current block using Element.getBoundingClientRect.

Then, you can find the current selection's bounding rect. Here's some discussion on it as a start:

http://stackoverflow.com/questions/8456652/how-to-get-the-pixel-offset-from-the-current-caret-position-in-an-iframe-with-co

However...

Having written and worked on a WYSIWYG editor, I can tell you several problems you are going to run into.

(1) Different browser's will have different edge cases on what will and won't work. I believe the Editor my team previously wrote (we were originally going to release it as a product) has the best documented list of edge cases and how we solved them. It can be found here: https://github.com/thesunny/SnapEditor/tree/master/coffeescripts/core/range with my apologies that it is in CoffeeScript if you are unfamiliar with it. It's pretty straightforward I thing to read though and the comments, which outnumber the code, is plain English. ;)

The differences and documentation on it were mostly done by one of my team Wesley Wong.

(2) Although there is a method getBoundingClientRect on the Range object, this does not always work. The solution is to have to insert a DOM element and measure that instead and then clean it up which we can do by deleting it. The issue is that with React, after you delete the DOM element, the DOM may still look different. For example, if you inserted the DOM element into a text node then deleted it, you'll probably end up with two text nodes. You can "normalize" the nodes using this method https://developer.mozilla.org/en-US/docs/Web/API/Node/normalize but I'm not entirely clear how React renders and expects it's nodes. For example, React may expect, in some cases, for the nodes to remain denormalized in which case normalizing the entire block may put the DOM in an unexpected state. Perhaps somebody more familiar with React internals can chime in whether we can use normalize safely.

Assuming that the normalize is a safe operation, I don't think it would be too difficult to get this code to work by using the SnapEditor measuring code (I've elected to open source the entire code base) to account for browser differences.

Note that it currently says LGPL but I'm willing to change this to the most permissive license and do whatever needs to be done for Facebook to accept the source code.

**Comment by thesunny** [comment]
Augh, it also looks like somebody solved this issue using a different approach I suggested already. The thing is, I even read about it before and completely forgot.

It's near the bottom of the comment thread...
https://github.com/facebook/draft-js/issues/203

I've left the previous comment up because I think it's still an interesting and valid approach to solving atomic block navigation.

**Comment by delijah** [comment]
Issue #203 is exactly what i am talking about. So i am closing this one...
