### ISSUE TITLE
Draft.js unminified says Immutable is undefined 

### ISSUE THREAD

**Issue by conor909** [facebook/draft-js#435]
Im trying to import the unminified draft.js by importing directly from jspm:
`import { Editor, EditorState, RichUtils } from "jspm_packages/npm/draft-js@0.7.0/dist/draft.js";`

I need to use the unminified version but I'm still getting the following error, it happens with any interaction with the `Editor` component.
 
`invariant.js:13 Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.`

**Comment by zpao** [comment]
The dist file expects that `React` and `Immutable` are globals (it's a browser bundle) so if you are going to consume those directly you'll need to make sure those globals are available.

**Comment by conor909** [comment]
Its a single page app with jspm bringing in my dependencies to `index.html`.
So I presumed Id have access to each dependency.  Is this the wrong setup?

My config:
`"react": "npm:react@0.14.8"`
`"immutable": "npm:immutable@3.8.1"`
`"draft-js": "npm:draft-js@0.7.0"`

**Comment by zpao** [comment]
I don't know how jspm works. The npm packages do not set globals so if you're using those directly it's probably fine. But once you start reaching into files that aren't part of the commonjs package you'll likely encounter issues. Your initial comment indicates you're doing exactly that.

If you can't get it to work, we'll need a complete reproducible test case, otherwise there isn't much we can do.

**Comment by conor909** [comment]
I believe this is an issue with jspm and I need to upgrade versions, so I'll close this.

**Comment by shashiranjansingh** [comment]
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by shashiranjansingh** [comment]
- `eeeeeeeeeeeeeee****`
