### ISSUE TITLE
Freeze text but allow formatting

### ISSUE THREAD

**Issue by jessica-pixvana** [facebook/draft-js#467]
I'd like to be able start off the editor with some given text and then only allow the user to format it, not edit the text itself. Basically, exactly like the color example with some default text, and only be able to style that text. Is there a way to do this?

**Comment by hellendag** [comment]
Can you use the `readOnly` prop for this? I'm not actually sure whether `onSelect` will pick up desired selection changes if you do use that.

**Comment by jessica-pixvana** [comment]
I tried that. When I add the `readOnly` prop, it appears to disable the onSelect and become totally static text.

**Comment by flarnie** [comment]
I think the short answer is that there is no easy way to do this with Draft.js currently. I don't expect we would add it as a feature unless demand increases. Hope you were able to find a work-around, sorry this wasn't supported.

**Comment by ChandanPHAI** [comment]
@jessica-pixvana Did you find any solution ? I am also looking for the same Freeze text but allow formatting thing.

**Comment by guillaumedsde** [comment]
Hello, interested in a feature like that as well :)

**Comment by silvergravel** [comment]
Hi for anyone else who is stuck, i found a decent workaround.
basically:
```
//if 
window.getSelection().anchorOffset !== window.getSelection().focusOffset
//then
<Editor readOnly={false}/> //by switching a state variable
```
i also make an interface visible to do whatever i want to the selected text,

this interface ultimately has a CTA that fires a function which does whatever ( in my case creates an `entity` and then a `RichUtils.toggleLink()`) and at the end of this function, i switch that state variable back to `false` making the `<Editor readOnly = {true}/>` and its back to being uneditable again. So you can fire whatever function you want that changes the `EditorState`, and it will work, because for that window of time when the function fires, the `Editor` is NOT `readOnly`

Now at the time when the text is selected, the editor is editable technically. So one would think that, at the time of selection, if user hits a delete or whatever other button, stuff would end up getting edited. But it doesnt! I have no idea why. work well for me though.
