### ISSUE TITLE
Missing .set() method for EditorState in the documentation

### ISSUE THREAD

**Issue by klimksh** [facebook/draft-js#579]
In the [documentation example](https://facebook.github.io/draft-js/docs/advanced-topics-decorators.html#setting-new-decorators) set() is used:
`return EditorState.set(editorState, {decorator: onlyHashtags});`

However, in EditorState documentation .set() method is missing.

**Comment by mjomble** [comment]
The `set` method is inherited from `Immutable.Record`.
The documentation does mention this inheritance, although it stresses that the Immutable API should not be used directly, which kind of conflicts with the example.
And I also just noticed that the documentation for `Record` actually doesn't mention the `set` method.
So there's some room for improvement :)

**Comment by flarnie** [comment]
Thanks for bringing this up! On the one hand we don't want to duplicate the Immutable.js documentation, but maybe erring on the side of giving more information rather than less is good here. Hopefully @tylercraft 's PR will clear this up - we will be continuing to improve the docs, so keep the feedback coming. :)
