### ISSUE TITLE
Visually retaining selection after blur

### ISSUE THREAD

**Issue by davisml** [facebook/draft-js#60]
How would you recommend visually retaining the text selection even when the editor is blurred? My initial thought was to use inline styles but I'd like to get a second opinion.

See the example below. I'd like the selection to still show when changing text properties from an input.

![screen shot 2016-02-24 at 10 43 45 am](https://cloud.githubusercontent.com/assets/53096/13288690/879d8262-dae3-11e5-9c19-2928a9897244.png)
![screen shot 2016-02-24 at 10 43 48 am](https://cloud.githubusercontent.com/assets/53096/13288696/8bea947c-dae3-11e5-96e6-2e83e1833665.png)

**Comment by hellendag** [comment]
Awesome screenshots. This looks really nice.

Since the browser can't maintain both cursor positions simultaneously, there's no native solution for this. In Notes, I have tried two different approaches:

1. What you have here, which just moves the selection over to the flyout. Here, one would just hope that the user isn't too thrown off by the selection disappearing. This is what is currently in production on Notes. I basically punted on it since people didn't seem too confused when using it.

2. My initial approach, which I replaced with the option above. Create a "fake" entity, either a "LINK_PLACEHOLDER" (or something like that) or a "LINK" with an empty href. In your decorator component, then you would check whether it's a fake link, and decorate it in some way to indicate that it is the target text. If you accept the link entry, replace the entity or merge in the data with the new href. If you reject the link entry, you'd just set the entity back to null on that range.

Inline styles could work there too. You'd just remove the style after accepting or canceling the link entry.
