### ISSUE TITLE
Add more options (customize editor)

### ISSUE THREAD

**Issue by stevecat1** [facebook/draft-js#688]
Hello,

I am new here & can't figure out how can i add more buttons like `<sub>`  `<sup>`  `<mark>` etc. apart from given tags into editor.

I have added in inline style

>       var INLINE_STYLES = [
>         {label: 'Bold', style: 'BOLD'},
>         {label: 'Italic', style: 'ITALIC'},
>         {label: 'Underline', style: 'UNDERLINE'},
>         {label: 'Monospace', style: 'CODE'},
>         {label: 'Strikethrought', style: 'STRIKETHROUGH'},
>         {label: 'Sup', style: 'SUPERSCRIPT'},
>         {label: 'Sub', style: 'SUBSCRIPT'},
>       ]; 

And 

     const styleMap = {
        CODE: {
          backgroundColor: 'rgba(0, 0, 0, 0.05)',
          fontFamily: '"Inconsolata", "Menlo", "Consolas", monospace',
          fontSize: 16,
          padding: 2,
        },
        'STRIKETHROUGH': {
          textDecoration: 'line-through',
        },
        'SUPERSCRIPT': {
          verticalAlign: 'super',
        },
        'SUBSCRIPT': {
          verticalAlign: 'sub',
        },
      };
 but not getting output into html for sup & sub even after using draft-js-export-html.

Please tell me, Am I doing correctly .?

**Comment by davidchang** [comment]
Hi @stevecat1 , my apologies for being so unresponsive to this issue. I am not sure what you're asking exactly, but are you mostly concerned with retaining your style attributes when you export to HTML? in that case, this would be a specific issue that ought to be directed towards the [draft-js-export-html](https://github.com/sstur/draft-js-export-html) project. This issue looks like it may be relevant to you: https://github.com/sstur/draft-js-export-html/issues/10

I'm going to close this (just because we have 203 issues right now and I'm trying to work through a lot of these questions), but feel free to reopen if you have any issues, or to join the Draft Slack channel where others will be available to answer questions more quickly :)

**Comment by andpor** [comment]
draftjs convertFromHTML drops <sub> and <sup> tags. Is there a way to instruct it not to drop these standard tags?
