### ISSUE TITLE
The onTab event was invalid

### ISSUE THREAD

**Issue by imjeen** [facebook/draft-js#704]
To add the onTab event for the Editor component, but it was not work. I just did like the rich example.

`this.onTab = (event)=> this.onChange( RichUtils.onTab(event, this.state.editorState, 4) );`

I don't know whether it was a problem, could you have a look at it?

**Comment by imjeen** [comment]
Maybe, it got it wrong. 

It is only valid when I use the UL or OL.

**Comment by mzbac** [comment]
@imjeen I think it supposed to only support UL and OL
https://github.com/facebook/draft-js/blob/69890ed57b5f4256cc93ae8e9ea178296851a23e/src/model/modifier/RichTextEditorUtil.js#L190

**Comment by kenjiru** [comment]
It's not working for me either. I'm using draft-js@0.9.1

**Comment by davidchang** [comment]
per the code @mzbac linked, RichUtils.onTab is only intended for blocks that are ordered or unordered lists. Normal contenteditable doesn't allow tab to perform an indent (rather, tabbing changes the focus on the page), but you could augment tab so that it artificially inserts an indent if that's the behavior you're going for.

is anything else needed on this issue?

**Comment by kenjiru** [comment]
Ok, so my problem was caused because I didn't include Draft.css. Now it works fine.

**Comment by davidchang** [comment]
Closing as no more issues. https://github.com/facebook/draft-js/issues/716 was opened and was somewhat related.
