### ISSUE TITLE
Wrong height after componentDidUpdate

### ISSUE THREAD

**Issue by santiagopuentep** [facebook/draft-js#712]
Bug: fill a line with characters and type one more to create a new line and check the height of the component on componentDidUpdate: the height is the one of the single line instead of two lines.

Check this jsFiddle.

https://jsfiddle.net/u6sa6zcp/1/

In my project I need to make sure that the container of the editor has a certain size depending on the number of lines, that´s why I need the correct height of the editor after the update.

The problem seems to be that draft.js uses onkeydown and the conteneeditable updates it´s size after react makes the update. Using requestAnimationFrame after componentDidUpdate gives the correct height.

**Comment by davidchang** [comment]
@santiagopuentep - thanks for opening this bug. While it is a clearly a bug regarding your use case, I'm not sure that we can do anything in the codebase to address this specifically - I think the real issue lies within React (it's a side effect of trying to run imperative commands on DOM refs after updates). If you feel strongly about this, please feel free to reopen, but I'm going to ahead and mark this as a wontfix and close it.
