### ISSUE TITLE
Link example not creating clickable links

### ISSUE THREAD

**Issue by candronikos** [facebook/draft-js#768]
BUG

The link example [here](https://github.com/facebook/draft-js/blob/master/examples/link/link.html) works fine to create the `<a>` element. Clicking the link doesn't work though.

I rebuilt the code in the master branch and used local copies of the other javascript dependencies but that's the only difference.

I expected for the `<a></a>` element to redirect me to the url provided.

Used current master commit: `341a49d01a492ff5a55a3ee8056e007538e2289a` and tested on Chrome and Firefox.

**Comment by CAYdenberg** [comment]
I got the same thing.

The links do work if readOnly={true}.

**Comment by aarboleda1** [comment]
@CAYdenberg do you pass down the readOnly={true} prop inside the <a> tag?

**Comment by voidstarfire** [comment]
That link is a 404 now. Does anyone have an example? Struggling to find out how to do something that should be really basic 👎

**Comment by florianmartens** [comment]
some problem here.

**Comment by mrkev** [comment]
Links in `contenteditable="true"` contexts are not clickable— this is not a bug but rather how browsers work. Hence it works on `readOnly` mode, since that sets `contenteditable="false"`.

A real editor, can do one of several things:

- Set an onClick handler on the `<a />` tag. This probably would also require accessibility considerations (aria tagging).
- Make the link hover-able, and put the clickable link in a tooltip. This is what I see many editors do since it prevents accidental clicks when editing. 

If someone wants to improve the example either with documentation mentioning why the links are not clickable, or by implementing one of the options above, I'd be happy to merge a PR (:

**Comment by NZY1337** [comment]
my solution

export const Link = (props) => {
	const { contentState, entityKey } = props;
	const { url } = contentState.getEntity(entityKey).getData();
	return (
		<a
			className='link'
			href={url}
			onClick={() => {
				const link = document.getElementsByClassName("link")[0];
				const url = link.href;
				window.open(url, "_blank");
			}}
			rel='noopener noreferrer'
			target='_blank'
			aria-label={url}>
			{props.children}
		</a>
	);
};

**Comment by NZY1337** [comment]
my solution:

export const Link = (props) => {
	const { contentState, entityKey } = props;
	const { url } = contentState.getEntity(entityKey).getData();

	return (
		<a
			className='link'
			href={url}
			onClick={(e) => {
				const link = e.target.parentElement.parentElement;
				const url = link.href;
				window.open(url, "_blank");
			}}
			rel='noopener noreferrer'
			target='_blank'
			aria-label={url}>
			{props.children}
		</a>
	);
};
