### ISSUE TITLE
No support for pictures and videos in `convertFromHTML `

### ISSUE THREAD

**Issue by MinJieLiu** [facebook/draft-js#778]
No support for pictures and videos in `convertFromHTML `

**Comment by flarnie** [comment]
Hi @MinJieLiu - I'm wondering if this issue is related to the API changes that are present on master but not in Draft version 0.9.1? You may find that the examples work on the master branch, but that those same examples will not work with Draft 0.9.1. For more detail about that see issue #816.

If this is different then please let us know more info - what version of Draft were you using, and what errors (if any) appeared in the console? What browser were you using? Screenshots or a jsfiddle to reproduce would be super helpful as a bonus.

Thanks for reporting the bug and we look forward to hearing from you.

**Comment by MinJieLiu** [comment]
It was in version 0.10
