### ISSUE TITLE
Uncaught TypeError: contentBlock.getText is not a function in tweet example

### ISSUE THREAD

**Issue by MarkMurphy** [facebook/draft-js#794]
Using the most recent release of the draft-js npm package (at time of writing v0.9.1), I get the following error in the `findWithRegex` method from the tweet example:

```
Uncaught TypeError: contentBlock.getText is not a function
```

I believe these lines are the problem:

https://github.com/facebook/draft-js/blob/master/examples/tweet/tweet.html#L87
https://github.com/facebook/draft-js/blob/master/examples/tweet/tweet.html#L91

It doesn't appear that contentState is passed as a parameter to those methods. They only receive two arguments: `contentBlock` and `callback`

The documentation here has the correct (or outdated?) strategy function definitions: https://facebook.github.io/draft-js/docs/advanced-topics-decorators.html#compositedecorator

It looks like `contentState` was introduced recently here: https://github.com/facebook/draft-js/commit/c6274c592fc1aef58b8e30c289f323f5ede148fc

Recommendations?

**Comment by tobiasandersen** [comment]
You're right in that `contentState` has changed (the entity map has been moved to it). However, those changes, along with the code you're referring to, hasn't been released yet. I _believe_ they're holding it for v. 1.0. Here's the tweet example in the latest release: https://github.com/facebook/draft-js/blob/0.9.1/examples/tweet/tweet.html. I just cloned the project and checked out that release and it appears to be working fine.

**Comment by flarnie** [comment]
You're right @tobiasandersen - thanks for explaining. We are indeed planning to release the new API in v0.10.0, and the examples on master reflect that. And thanks @MarkMurphy for flagging the indescrepancy.

Since this has caused confusion, we opened an issue to include examples with both the old and new syntax - #816.

Hopefully things are clear now - feel free to reopen or comment on #816 if any questions remain.
