### ISSUE TITLE
convertFromHTML rejects error Cannot read property 'map' of undefined(…)

### ISSUE THREAD

**Issue by optimatex** [facebook/draft-js#809]
**Do you want to request a *feature* or report a *bug*?**
report a bug
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
I get code from this docs https://facebook.github.io/draft-js/docs/api-reference-data-conversion.html#content and try to implement it but got `TypeError: Cannot read property 'map' of undefined(…)`

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
versions of Draft.js draft-js@0.9.1 
browser=chrome  OS=windows 8.

**Comment by oscarmorrison** [comment]
+1

**Comment by saymy** [comment]
+1

**Comment by stagfoo** [comment]
+1

**Comment by tobiasandersen** [comment]
That example is actually for a future release and won't work with version 0.9.1 (latest on npm). It's a bit misleading that this is on the docs already. I don't think that's intentional? (cc @flarnie)

I just created a PR with [an example for 0.9.1](https://github.com/tobiasandersen/draft-js/blob/1c7499baeef5866af95481c48aa5db177762e0aa/examples/draft-0-9-1/convertFromHTML/convert.html). The main difference is that you should do this:
```
const blocksFromHTML = convertFromHTML(sampleMarkup);
const state = ContentState.createFromBlockArray(blocksFromHTML);
```
rather than:
```
const blocksFromHTML = convertFromHTML(sampleMarkup);
const state = ContentState.createFromBlockArray(
  blocksFromHTML.contentBlocks,
  blocksFromHTML.entityMap,
);
```



Support for converting images was also added recently, so that won't work for 0.9.1, but the rest should.

**Comment by flarnie** [comment]
Thanks @tobiasandersen for updating the example and documentation.

**Comment by emorris** [comment]
https://draftjs.org/docs/api-reference-data-conversion/  4 years and the example is the same
