### ISSUE TITLE
Upgrade to Gulp 4.0

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#813]
Our build process currently uses [Gulp 3.9.*](https://github.com/facebook/draft-js/blob/master/package.json#L55) and [Gulp 4.0 has been released](https://github.com/gulpjs/gulp/blob/4.0/CHANGELOG.md#400) with some API changes, improvements, and performance boosts.
We should upgrade to Gulp 4.0 at some point. One change we can make then is [removing the dependency on the `run-sequence` module](https://www.npmjs.com/package/run-sequence#please-note), which will be replaced by `gulp.series` and `gulp.parallel`.

If you're interested in understanding the build system for transpiling an open source project to support ES6 and Flow, questions and PRs are welcome.

**Comment by tobiasandersen** [comment]
I started looking at this and have a notes/questions:

Version 4.0 hasn't yet been published to npm. So to use it, we need to add it by pointing to their repo, i.e. `"gulp": "gulpjs/gulp#4.0"`. But this breaks the `'check-dependencies'`task.

Gulp now recommends using plain functions rather than named tasks, see their [example gulpfile.js file](https://github.com/gulpjs/gulp/blob/4.0/README.md#sample-gulpfilejs). Named tasks still work, but do you think we should update anyway? 

Replacing `run-sequence` with `gulp.series` and `gulp.parallel` seems to be working fine.

Should I create a PR with this or is it better to wait for version 4.0 to be published on npm?

**Comment by flarnie** [comment]
Thanks for looking into this! I didn't realize Gulp 4.0 isn't published to npm - for anyone following this issue, we can track progress on that here: https://github.com/gulpjs/gulp/issues/1486. 
Let's put this on hold. Closing this issue for now. Thanks again @tobiasandersen!
