### ISSUE TITLE
Is there a way to distinguish what changed in onChange callback?

### ISSUE THREAD

**Issue by bajalovic** [facebook/draft-js#830]
As I experienced, `onChange` callback will be called when there is a selection change (for example when editor get focus) and when content changes (you type in something).

How can i distinguish what changed? Should I compare editor state?

For example, I would like to have a Save button that will only be shown if there are some changes. Currently, button will be displayed every time editor receives focus.

**Comment by tobiasandersen** [comment]
You're right in that `onChange` is called every time the `editorState` changes. And since the `editorState` holds both the `selectionState` and the `contentState`, it will change both when there's a content edit, and when the selection/focus changes.

If you want know if the change that triggered the `onChange` method was in the `contentState` or in the `selectionState`, you could compare them with their old values:

```
function onChange(newState) {
  const currentContentState = this.state.editorState.getCurrentContent()
  const newContentState = newState.getCurrentContent()

  if (currentContentState !== newContentState) {
    // There was a change in the content  
  } else {
    // The change was triggered by a change in focus/selection
  }
}
```

Now, if you know that the change was in the contentState, you can get some more info by calling: [newState.getLastChangeType()](https://facebook.github.io/draft-js/docs/api-reference-editor-state.html#lastchangetype). It _should_ return any of [these values](https://github.com/facebook/draft-js/blob/master/docs/APIReference-EditorChangeType.md#values) (unless you, or some plugin you've added, have created new change types).

**Comment by bajalovic** [comment]
Thanks @tobiasandersen this works.
