### ISSUE TITLE
Fails on npm install with missing gulp-concat dependency

### ISSUE THREAD

**Issue by aduth** [facebook/draft-js#853]
I ran `npm install` from a fresh downloaded zip to try out included examples, following example instructions from the root README, but encountered the following error upon install:

https://gist.github.com/aduth/ea0ac58249b2b9857e97498108b83a51

Specifically, it seems this is an issue of the `gulp-clean-css` defining `gulp-concat` in `devDependencies` instead of `dependencies`, meaning it is not installed by Draft.js. This appears to be fixed in https://github.com/scniro/gulp-clean-css/commit/98700d453f04d638ad26f117a337f91b81d395a3 but no release has been made yet of `gulp-clean-css` including the fix.

Current workaround is to manually install `gulp-concat` after install, then proceeding with `npm run build`.

Should be a matter of installing the new version of `gulp-clean-css` when it's made available.

**Comment by davidchang** [comment]
@aduth - thank you for reporting this, my apologies for the late response. Looks like gulp-clean-css was at 2.2.0 the day you opened this task, but since then has had at least 2 updates (so it's now at 2.2.2) - which should have been picked up automatically here: https://github.com/facebook/draft-js/blob/7390e2972145494146202c3d3480eb9509dc90d4/package.json#L59

furthermore, i just pulled down the zip of master and ran npm install && npm run build without any problems.

I'm going to close this, but please feel free to reopen if any issues!

**Comment by aduth** [comment]
Thanks for the response @davidchang. I can confirm it works without issue now.
