### ISSUE TITLE
CompositeDecorators does not work for adjacent ContentBlocks

### ISSUE THREAD

**Issue by prashantagarwal** [facebook/draft-js#896]
**Do you want to request a *feature* or report a *bug*?**
Bug

So I was trying to add two consecutive hashtags using draft-js composite decorator example.
something like `#try#this`

But this does not work.
I have more use cases similar like this.
After some digging I found out in composite decorator callback we check if matching range is already occupied by another decorator. https://github.com/facebook/draft-js/blob/master/src/model/decorators/CompositeDraftDecorator.js#L63

Is there some specific reason to do this?

**Comment by davidchang** [comment]
hi @prashantagarwal - thanks for opening up this issue. Were you referring to this file: https://github.com/facebook/draft-js/blob/master/examples/draft-0-9-1/tweet/tweet.html#L85 when you referenced the "composite decorator example" ?

I think this is just a case where the regular expression for the decorator is just overly simplistic - it is just looking for the initial '#' character and then continues until it doesn't have a character it can parse. Your other use cases, though, may be different.

As for why we check if the matching range is already occupied by another decorator - this is because we don't currently support nested decorators. This is something that has been discussed though (see https://github.com/facebook/draft-js/issues/542 or search "nested decorators")

That said, is this issue a dupe of #542 ? Is this issue basically an ask for nested decorators?

**Comment by prashantagarwal** [comment]
Hi @davidchang - thanks for getting back on this.
Actually I have a different problem than #542 

So I was decorating text that is enclosed by `{{ }}`
so I added a mention strategy and decorator for this.
Now this works fine if the scenario is some thing like this
`{{abc}} {{def}}`

but it fails when I try to do something like `{{abc}}{{def}}`

so you see these are two adjacent decorated blocks (not nested)
What I can made out of https://github.com/facebook/draft-js/blob/master/src/model/decorators/CompositeDraftDecorator.js#L93 is that **start** is coming out to be the index of the last character {{abc}**}**{{def}} . And I believe it should be {{abc}}**{**{def}}

Thanks

**Comment by prashantagarwal** [comment]
@davidchang I found out this was totally unrelated. After making some changes I tested with different decoration strategies, but the original code was actually correct. Sorry was causing trouble I am closing this issue.
