### ISSUE TITLE
Composing multiple ContentStates ?

### ISSUE THREAD

**Issue by Revln9** [facebook/draft-js#898]
**Do you want to request a *feature* or report a *bug*?**

FEATURE

**What is the current behavior?**

If you store your contentstate somewhere via convertToRaw and retrieve it later Via convertFromRaw , even if you apply it with EditorState.push() , it will replace the current content , i think this is not a bug but an expected behaviour , no? , however suppose i want to compose multiple contentstate in my current contentstate  like adding multiple senteces who are stored as RawContentsate how can i do this?,

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

here is a quick demo i came up with

https://jsfiddle.net/cbo1kqje/

**What is the expected behavior?**

A way to "MERGE" multiple ContentStates into the current ContentState

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

0.9.1

**Comment by davidchang** [comment]
@Revln9 - thanks for opening the issue, and thanks for coming up with the quick jsfiddle (that really helps a lot, and not many people actually add one that's relevant!). I'm not sure I understand you completely, but are you hoping for some sort of EditorState.replace method (where you replace the current state instead of pushing a new state)?

I'm also curious, do you have a specific use case underlying this request?

**Comment by Revln9** [comment]
Hi david , 

Yes i use draft js as a composable list of items where each item have its own style, alignement, color ...etc

If you make multiple items  and save EACH of them individually via `convertToRaw` , you cant compose them because when you load it via `convertFromRaw` it will return a new editor state and erase the previous one. In short terms, each item will replace the previous.
It will be nice if you give the ability to compose them at the current editor and to give some methods to APPEND Blocks to the current editorState , and not only replacing the entire state.

What do you think ?

 because when you start thinking about it , the first Tricky thing that will come up is the  styles positions...a good way to avoid this is to make calculation depending on the block limits.


One last thing to do is to bring the alignement state at the block level not at the entire editor i've managed to do this with some research but it was painful.  

Thanks for your time.

**Comment by davidchang** [comment]
Hi @Revln9 - thanks for the response. I am honestly still a bit skeptical that this is necessary to be supported at the core level. It seems like pretty unique behavior, to save pieces of the Draft contentState individually, then to compose them all together (though composing altogether asynchronously) instead of just saving them all together or combining them all together at a single point. i could see some argument if you have a HUGE contentState and are trying to do some sort of pagination, and I don't know that your other points about styles or alignment states are very relevant to your request for an append method.

also, append is really just a shorter replace method (you're replacing the state with the current contentState and manually appending your new state to it yourself)

**Comment by Revln9** [comment]
Yes , i understand that this is a bit "out of the scope" but suppose you wanna make an wysiwyg website builder with draft , and you want to store each 'component' as a snippet example : an image with styles, header, footer at you database and compose them to make your website pages ,  you will need something like this to do it , otherwise it will be painful to restyle each component every time...

Draft editor is so rich and customizable that it will be a shame to just use it to  format 2 lines of text...
I'm already working on it , i'll fork something or make a plugin of it ,  but i don't know yet exactly how to tackle this correctly , do you have some tips?

Text alignement ,  consider this as not dependent  to the first request but still is an important feature to have , and especially when your plugin does rich text editing. 

take a look at this , it has some nice design approachesa bout the methods used
https://quilljs.com/docs/api/#formatting

thanks

**Comment by flarnie** [comment]
Hi @Revln9 - just checking, were there any action items left on this issue? It sounds like the `redraft` plugin was helpful and I'm not sure if you still had requests/concerns to be addressed.

Thanks!

**Comment by flarnie** [comment]
Since there are no action items remaining here I'm closing this.
