### ISSUE TITLE
Question: Regarding examples license

### ISSUE THREAD

**Issue by pkasperczyk** [facebook/draft-js#900]
Hi,

in url https://github.com/facebook/draft-js/blob/master/LICENSE-examples there is a statement

"The examples provided by Facebook are for non-commercial testing and evaluation
purposes only. Facebook reserves all rights not expressly granted."

**Can we use some snippets of code from examples on public website, if it is for non-commercial purpose?**
For me it seems that someone may treat testing and evaluation time as a very long time, even if everythink is working well :), but maybe this sentence should be different understood

**Can we write our own code based on examples?**
Examples usually have a proper way, how to use API. If I cannot use some lines from examples, how can I use API?

Regards and Merry Christmas,
Pawel

**Comment by flarnie** [comment]
Interesting question! :)

My opinion is that the examples are intended to demonstrate patterns which you can use when writing your own code.

You are right that we couldn't write code using Draft without using the same API calls that are used in the examples. I'm pretty sure this is considered ok, because otherwise we couldn't really write code.

Did you have a specific use case that you're considering? If so I can get confirmation about specific uses of the example code.

Also tagging @zpao in case you have advice on answering this type of question, or who I should direct this type of question to.

**Comment by pkasperczyk** [comment]
Hello, thank you for the answer:

Our usecase:
We used draft-js for non-commercial website supporting volunteers during World Youth Days in 2016 and needed to use some patterns from [Rich HTML](https://github.com/facebook/draft-js/blob/master/examples/draft-0-10-0/rich/rich.html ) example.

**Comment by flarnie** [comment]
Hi again @pkasperczyk and thanks for replying! I'm sure that's a fine use of the patterns from the examples. Thanks for checking about this.
