### ISSUE TITLE
Add equivalence check method to EditorState

### ISSUE THREAD

**Issue by rmccue** [facebook/draft-js#949]
Right now, there's no public API to compare two different EditorState objects. Since EditorState is a wrapper around an Immutable Record, it's easy to compare two states by using `Immutable.is(state1.getImmutable(), state2.getImmutable())`, however `getImmutable` is explicitly marked "Not for public consumption."

It'd be great to have a public API equivalent for this, e.g. `state1.equals(state2)` (which would match the method on Immutable objects).

**Comment by jan4984** [comment]
does `==` work? because and property assignment in `Immutable` will return same js object.

**Comment by rmccue** [comment]
It does, but I believe it's possible to have two different Immutable Records with the same values (unless Immutable is doing some hidden memoization internally), hence the need for `Immutable.is`.

**Comment by vasymus** [comment]
var a = JSON.stringify(convertToRaw(body.getCurrentContent()))

**Comment by vasymus** [comment]
Maybe, walkaround ?
var a = JSON.stringify(convertToRaw(state1.getCurrentContent()))
var b = JSON.stringify(convertToRaw(state2.getCurrentContent()))
a === b

**Comment by flarnie** [comment]
You are right that `EditorState` is a wrapper around an Immutable Record, from the `Immutable.js` library.

However, in practice the `EditorState` instance is Immutable, in the sense that it should always be replaced rather than mutated.

For example, all the static methods for making changes to an `EditorState` instance will return a new instance of `EditorState`, so you should be able to just compare whether `editorStateA === editorStateB`, like so:
```
const editorStateA = EditorState.createEmpty();
// make an updated contentState and selectionState, then set those in editorState:
const editorStateB = EditorState.set(editorStateA, {currentContent: content, selection});
// editorStateA === editorStateB returns false
```

In practice we assume that if `editorStateA !== editorStateB` then they are different. See the `shouldComponentUpdate` check in the editor component:
https://github.com/facebook/draft-js/blob/master/src/component/contents/DraftEditorContents-core.react.js#L102-L105
